-----------------------------------------------------------------
-- Autogenerated by Thrift
--
-- DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
--  @generated
-----------------------------------------------------------------
{-# LANGUAGE OverloadedStrings #-}
{-# LANGUAGE BangPatterns #-}
{-# OPTIONS_GHC -fno-warn-unused-imports#-}
{-# OPTIONS_GHC -fno-warn-overlapping-patterns#-}
{-# OPTIONS_GHC -fno-warn-incomplete-patterns#-}
{-# OPTIONS_GHC -fno-warn-incomplete-uni-patterns#-}
{-# OPTIONS_GHC -fno-warn-incomplete-record-updates#-}
{-# LANGUAGE FlexibleContexts #-}
{-# LANGUAGE TypeFamilies #-}
{-# LANGUAGE TypeOperators #-}
module C.MyService.Client
       (MyService, my_function, my_functionIO, send_my_function,
        _build_my_function, recv_my_function, _parse_my_function)
       where
import qualified Control.Arrow as Arrow
import qualified Control.Concurrent as Concurrent
import qualified Control.Exception as Exception
import qualified Control.Monad as Monad
import qualified Control.Monad.Trans.Class as Trans
import qualified Control.Monad.Trans.Reader as Reader
import qualified Data.ByteString.Builder as ByteString
import qualified Data.ByteString.Lazy as LBS
import qualified Data.HashMap.Strict as HashMap
import qualified Data.Int as Int
import qualified Data.List as List
import qualified Data.Proxy as Proxy
import qualified Data.Text as Text
import qualified Data.Text.Encoding as Text
import qualified Facebook.Thrift.Annotation.Thrift.Thrift.Types
       as Facebook.Thrift.Annotation.Thrift.Thrift
import qualified Prelude as Prelude
import qualified Thrift.Binary.Parser as Parser
import qualified Thrift.Codegen as Thrift
import qualified Thrift.Protocol.ApplicationException.Types
       as Thrift
import Data.Monoid ((<>))
import Prelude ((==), (=<<), (>>=), (<$>), (.))
import C.Types

data MyService

my_function ::
              (Thrift.Protocol p, Thrift.ClientChannel c,
               (Thrift.<:) s MyService) =>
              Annotated_string -> Thrift.ThriftM p c s Int.Int64
my_function __field__param
  = do Thrift.ThriftEnv _proxy _channel _opts _counter <- Reader.ask
       Trans.lift
         (my_functionIO _proxy _channel _counter _opts __field__param)

my_functionIO ::
                (Thrift.Protocol p, Thrift.ClientChannel c,
                 (Thrift.<:) s MyService) =>
                Proxy.Proxy p ->
                  c s ->
                    Thrift.Counter ->
                      Thrift.RpcOptions -> Annotated_string -> Prelude.IO Int.Int64
my_functionIO _proxy _channel _counter _opts __field__param
  = do (_handle, _sendCob, _recvCob) <- Thrift.mkCallbacks
                                          (recv_my_function _proxy)
       send_my_function _proxy _channel _counter _sendCob _recvCob _opts
         __field__param
       Thrift.wait _handle

send_my_function ::
                   (Thrift.Protocol p, Thrift.ClientChannel c,
                    (Thrift.<:) s MyService) =>
                   Proxy.Proxy p ->
                     c s ->
                       Thrift.Counter ->
                         Thrift.SendCallback ->
                           Thrift.RecvCallback ->
                             Thrift.RpcOptions -> Annotated_string -> Prelude.IO ()
send_my_function _proxy _channel _counter _sendCob _recvCob
  _rpcOpts __field__param
  = do _seqNum <- _counter
       let
         _callMsg
           = LBS.toStrict
               (ByteString.toLazyByteString
                  (_build_my_function _proxy _seqNum __field__param))
       Thrift.sendRequest _channel
         (Thrift.Request _callMsg
            (Thrift.setRpcPriority _rpcOpts Thrift.NormalPriority))
         _sendCob
         _recvCob

recv_my_function ::
                   (Thrift.Protocol p) =>
                   Proxy.Proxy p ->
                     Thrift.Response -> Prelude.Either Exception.SomeException Int.Int64
recv_my_function _proxy (Thrift.Response _response _)
  = Monad.join
      (Arrow.left (Exception.SomeException . Thrift.ProtocolException)
         (Parser.parse (_parse_my_function _proxy) _response))

_build_my_function ::
                     Thrift.Protocol p =>
                     Proxy.Proxy p ->
                       Int.Int32 -> Annotated_string -> ByteString.Builder
_build_my_function _proxy _seqNum __field__param
  = Thrift.genMsgBegin _proxy "my_function" 1 _seqNum <>
      Thrift.genStruct _proxy
        (Thrift.genField _proxy "param" (Thrift.getStringType _proxy) 2 0
           (Thrift.genText _proxy __field__param)
           : [])
      <> Thrift.genMsgEnd _proxy

_parse_my_function ::
                     Thrift.Protocol p =>
                     Proxy.Proxy p ->
                       Parser.Parser (Prelude.Either Exception.SomeException Int.Int64)
_parse_my_function _proxy
  = do Thrift.MsgBegin _name _msgTy _ <- Thrift.parseMsgBegin _proxy
       _result <- case _msgTy of
                    1 -> Prelude.fail
                           "my_function: expected reply but got function call"
                    2 | _name == "my_function" ->
                        do let
                             _idMap = HashMap.fromList [("my_function_success", 0)]
                           _fieldBegin <- Thrift.parseFieldBegin _proxy 0 _idMap
                           case _fieldBegin of
                             Thrift.FieldBegin _type _id _bool -> do case _id of
                                                                       0 | _type ==
                                                                             Thrift.getI64Type
                                                                               _proxy
                                                                           ->
                                                                           Prelude.fmap
                                                                             Prelude.Right
                                                                             (Thrift.parseI64
                                                                                _proxy)
                                                                       _ -> Prelude.fail
                                                                              (Prelude.unwords
                                                                                 ["unrecognized exception, type:",
                                                                                  Prelude.show
                                                                                    _type,
                                                                                  "field id:",
                                                                                  Prelude.show _id])
                             Thrift.FieldEnd -> Prelude.fail "no response"
                      | Prelude.otherwise -> Prelude.fail "reply function does not match"
                    3 -> Prelude.fmap (Prelude.Left . Exception.SomeException)
                           (Thrift.parseStruct _proxy ::
                              Parser.Parser Thrift.ApplicationException)
                    4 -> Prelude.fail
                           "my_function: expected reply but got oneway function call"
                    _ -> Prelude.fail "my_function: invalid message type"
       Thrift.parseMsgEnd _proxy
       Prelude.return _result