-----------------------------------------------------------------
-- Autogenerated by Thrift
--
-- DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
--  @generated
-----------------------------------------------------------------
{-# LANGUAGE OverloadedStrings #-}
{-# LANGUAGE BangPatterns #-}
{-# OPTIONS_GHC -fno-warn-unused-imports#-}
{-# OPTIONS_GHC -fno-warn-overlapping-patterns#-}
{-# OPTIONS_GHC -fno-warn-incomplete-patterns#-}
{-# OPTIONS_GHC -fno-warn-incomplete-uni-patterns#-}
{-# OPTIONS_GHC -fno-warn-incomplete-record-updates#-}
{-# LANGUAGE GeneralizedNewtypeDeriving #-}
module RecursiveAnnotation.Types (T, x, Ann(Ann, ann_i)) where
import qualified Control.DeepSeq as DeepSeq
import qualified Control.Monad as Monad
import qualified Control.Monad.ST.Trans as ST
import qualified Control.Monad.Trans.Class as Trans
import qualified Data.Aeson as Aeson
import qualified Data.Aeson.Types as Aeson
import qualified Data.Default as Default
import qualified Data.HashMap.Strict as HashMap
import qualified Data.Hashable as Hashable
import qualified Data.Int as Int
import qualified Data.List as List
import qualified Data.Ord as Ord
import qualified Prelude as Prelude
import qualified Thrift.Binary.Parser as Parser
import qualified Thrift.CodegenTypesOnly as Thrift
import Control.Applicative ((<|>), (*>), (<*))
import Data.Aeson ((.:), (.:?), (.=), (.!=))
import Data.Monoid ((<>))
import Prelude ((.), (<$>), (<*>), (>>=), (==), (/=), (<), (++))

type T = Int.Int64

x :: Ann
x = (Default.def :: Ann){ann_i = 44}

newtype Ann = Ann{ann_i :: T}
              deriving (Prelude.Eq, Prelude.Show, Prelude.Ord)

instance Aeson.ToJSON Ann where
  toJSON (Ann __field__i)
    = Aeson.object ("i" .= __field__i : Prelude.mempty)

instance Thrift.ThriftStruct Ann where
  buildStruct _proxy (Ann __field__i)
    = Thrift.genStruct _proxy
        (Thrift.genField _proxy "i" (Thrift.getI64Type _proxy) 1 0
           (Thrift.genI64 _proxy __field__i)
           : [])
  parseStruct _proxy
    = ST.runSTT
        (do Prelude.return ()
            __field__i <- ST.newSTRef Default.def
            let
              _parse _lastId
                = do _fieldBegin <- Trans.lift
                                      (Thrift.parseFieldBegin _proxy _lastId _idMap)
                     case _fieldBegin of
                       Thrift.FieldBegin _type _id _bool -> do case _id of
                                                                 1 | _type ==
                                                                       Thrift.getI64Type _proxy
                                                                     ->
                                                                     do !_val <- Trans.lift
                                                                                   (Thrift.parseI64
                                                                                      _proxy)
                                                                        ST.writeSTRef __field__i
                                                                          _val
                                                                 _ -> Trans.lift
                                                                        (Thrift.parseSkip _proxy
                                                                           _type
                                                                           (Prelude.Just _bool))
                                                               _parse _id
                       Thrift.FieldEnd -> do !__val__i <- ST.readSTRef __field__i
                                             Prelude.pure (Ann __val__i)
              _idMap = HashMap.fromList [("i", 1)]
            _parse 0)

instance DeepSeq.NFData Ann where
  rnf (Ann __field__i) = DeepSeq.rnf __field__i `Prelude.seq` ()

instance Default.Default Ann where
  def = Ann Default.def

instance Hashable.Hashable Ann where
  hashWithSalt __salt (Ann _i) = Hashable.hashWithSalt __salt _i