# https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-syntax-for-github-actions
name: CI
on: [push, pull_request]

jobs:
  ci:
    strategy:
      fail-fast: false
      matrix:
        ghc: [8.4.4]
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/donsbot/hsthrift/ci-base:ghcup-arm64v8
      options: --cpus 2
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install folly, fizz, wangle, rsocket-cpp, fbthrift
        run:  ./install_deps.sh --nuke
      - name: Install ${{ matrix.ghc }}
        run: ghcup install ghc ${{ matrix.ghc }} --set
      - name: Install cabal-install-3.6
        run: ghcup install cabal -u https://downloads.haskell.org/~cabal/cabal-install-3.6.0.0/cabal-install-3.6.0.0-aarch64-linux.tar.xz 3.6.0.0 --set
      - name: Add GHC and cabal to PATH
        run: echo "$HOME/.ghcup/bin" >> $GITHUB_PATH
      - name: Populate hackage index
        run: cabal update
      - name: Generate C++ code from thrift files
        run: make thrift-cpp
      - name: Build everything up to thrift-compiler
        run: cabal build --project-file=ci.cabal.project exe:thrift-compiler
      - name: Generate Haskell code from thrift files
        run: make thrift-hs
      - name: Generate source distributions for all packages
        run: cabal sdist --project-file=ci.cabal.project all
      - name: Unpack source distributions in new directory
        run: |
          mkdir _sdists
          cd _sdists
          for f in $(ls ../dist-newstyle/sdist/*.tar.gz); do
            tar xzf $f;
          done
          cp ../ci-sdist.cabal.project cabal.project
          cd ..
      - name: Build all packages
        run: cabal build all
        working-directory: ./_sdists
      - name: Run testsuites
        run: cabal test mangle fb-util thrift-compiler thrift-lib thrift-cpp-channel thrift-server thrift-tests --keep-going
        working-directory: ./_sdists
