-----------------------------------------------------------------
-- Autogenerated by Thrift
--
-- DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
--  @generated
-----------------------------------------------------------------
{-# LANGUAGE OverloadedStrings #-}
{-# LANGUAGE BangPatterns #-}
{-# OPTIONS_GHC -fno-warn-unused-imports#-}
{-# OPTIONS_GHC -fno-warn-overlapping-patterns#-}
{-# OPTIONS_GHC -fno-warn-incomplete-patterns#-}
{-# OPTIONS_GHC -fno-warn-incomplete-uni-patterns#-}
{-# OPTIONS_GHC -fno-warn-incomplete-record-updates#-}
{-# LANGUAGE FlexibleContexts #-}
{-# LANGUAGE TypeFamilies #-}
{-# LANGUAGE TypeOperators #-}
module Bidi.TestBiDiService.Client
       (TestBiDiService, echo, echoIO, send_echo, _build_echo, recv_echo,
        _parse_echo, echoWithResponse, echoWithResponseIO,
        send_echoWithResponse, _build_echoWithResponse,
        recv_echoWithResponse, _parse_echoWithResponse, intStream,
        intStreamIO, send_intStream, _build_intStream, recv_intStream,
        _parse_intStream, canThrow, canThrowIO, send_canThrow,
        _build_canThrow, recv_canThrow, _parse_canThrow)
       where
import qualified Control.Arrow as Arrow
import qualified Control.Concurrent as Concurrent
import qualified Control.Exception as Exception
import qualified Control.Monad as Monad
import qualified Control.Monad.Trans.Class as Trans
import qualified Control.Monad.Trans.Reader as Reader
import qualified Data.ByteString.Builder as ByteString
import qualified Data.ByteString.Lazy as LBS
import qualified Data.HashMap.Strict as HashMap
import qualified Data.Int as Int
import qualified Data.List as List
import qualified Data.Proxy as Proxy
import qualified Data.Text as Text
import qualified Data.Text.Encoding as Text
import qualified Facebook.Thrift.Annotation.Thrift.Thrift.Types
       as Facebook.Thrift.Annotation.Thrift.Thrift
import qualified Prelude as Prelude
import qualified Thrift.Binary.Parser as Parser
import qualified Thrift.Codegen as Thrift
import qualified Thrift.Protocol.ApplicationException.Types
       as Thrift
import Data.Monoid ((<>))
import Prelude ((==), (=<<), (>>=), (<$>), (.))
import Bidi.Types

data TestBiDiService

echo ::
       (Thrift.Protocol p, Thrift.ClientChannel c,
        (Thrift.<:) s TestBiDiService) =>
       Thrift.ThriftM p c s ()
echo
  = do Thrift.ThriftEnv _proxy _channel _opts _counter <- Reader.ask
       Trans.lift (echoIO _proxy _channel _counter _opts)

echoIO ::
         (Thrift.Protocol p, Thrift.ClientChannel c,
          (Thrift.<:) s TestBiDiService) =>
         Proxy.Proxy p ->
           c s -> Thrift.Counter -> Thrift.RpcOptions -> Prelude.IO ()
echoIO _proxy _channel _counter _opts
  = do (_handle, _sendCob, _recvCob) <- Thrift.mkCallbacks
                                          (recv_echo _proxy)
       send_echo _proxy _channel _counter _sendCob _recvCob _opts
       Thrift.wait _handle

send_echo ::
            (Thrift.Protocol p, Thrift.ClientChannel c,
             (Thrift.<:) s TestBiDiService) =>
            Proxy.Proxy p ->
              c s ->
                Thrift.Counter ->
                  Thrift.SendCallback ->
                    Thrift.RecvCallback -> Thrift.RpcOptions -> Prelude.IO ()
send_echo _proxy _channel _counter _sendCob _recvCob _rpcOpts
  = do _seqNum <- _counter
       let
         _callMsg
           = LBS.toStrict
               (ByteString.toLazyByteString (_build_echo _proxy _seqNum))
       Thrift.sendRequest _channel
         (Thrift.Request _callMsg
            (Thrift.setRpcPriority _rpcOpts Thrift.NormalPriority))
         _sendCob
         _recvCob

recv_echo ::
            (Thrift.Protocol p) =>
            Proxy.Proxy p ->
              Thrift.Response -> Prelude.Either Exception.SomeException ()
recv_echo _proxy (Thrift.Response _response _)
  = Monad.join
      (Arrow.left (Exception.SomeException . Thrift.ProtocolException)
         (Parser.parse (_parse_echo _proxy) _response))

_build_echo ::
              Thrift.Protocol p =>
              Proxy.Proxy p -> Int.Int32 -> ByteString.Builder
_build_echo _proxy _seqNum
  = Thrift.genMsgBegin _proxy "echo" 1 _seqNum <>
      Thrift.genStruct _proxy []
      <> Thrift.genMsgEnd _proxy

_parse_echo ::
              Thrift.Protocol p =>
              Proxy.Proxy p ->
                Parser.Parser (Prelude.Either Exception.SomeException ())
_parse_echo _proxy
  = do Thrift.MsgBegin _name _msgTy _ <- Thrift.parseMsgBegin _proxy
       _result <- case _msgTy of
                    1 -> Prelude.fail "echo: expected reply but got function call"
                    2 | _name == "echo" ->
                        do let
                             _idMap = HashMap.fromList []
                           _fieldBegin <- Thrift.parseFieldBegin _proxy 0 _idMap
                           case _fieldBegin of
                             Thrift.FieldBegin _type _id _bool -> do case _id of
                                                                       _ -> Prelude.fail
                                                                              (Prelude.unwords
                                                                                 ["unrecognized exception, type:",
                                                                                  Prelude.show
                                                                                    _type,
                                                                                  "field id:",
                                                                                  Prelude.show _id])
                             Thrift.FieldEnd -> Prelude.return (Prelude.Right ())
                      | Prelude.otherwise -> Prelude.fail "reply function does not match"
                    3 -> Prelude.fmap (Prelude.Left . Exception.SomeException)
                           (Thrift.parseStruct _proxy ::
                              Parser.Parser Thrift.ApplicationException)
                    4 -> Prelude.fail
                           "echo: expected reply but got oneway function call"
                    _ -> Prelude.fail "echo: invalid message type"
       Thrift.parseMsgEnd _proxy
       Prelude.return _result

echoWithResponse ::
                   (Thrift.Protocol p, Thrift.ClientChannel c,
                    (Thrift.<:) s TestBiDiService) =>
                   Text.Text -> Thrift.ThriftM p c s ()
echoWithResponse __field__initial
  = do Thrift.ThriftEnv _proxy _channel _opts _counter <- Reader.ask
       Trans.lift
         (echoWithResponseIO _proxy _channel _counter _opts
            __field__initial)

echoWithResponseIO ::
                     (Thrift.Protocol p, Thrift.ClientChannel c,
                      (Thrift.<:) s TestBiDiService) =>
                     Proxy.Proxy p ->
                       c s ->
                         Thrift.Counter -> Thrift.RpcOptions -> Text.Text -> Prelude.IO ()
echoWithResponseIO _proxy _channel _counter _opts __field__initial
  = do (_handle, _sendCob, _recvCob) <- Thrift.mkCallbacks
                                          (recv_echoWithResponse _proxy)
       send_echoWithResponse _proxy _channel _counter _sendCob _recvCob
         _opts
         __field__initial
       Thrift.wait _handle

send_echoWithResponse ::
                        (Thrift.Protocol p, Thrift.ClientChannel c,
                         (Thrift.<:) s TestBiDiService) =>
                        Proxy.Proxy p ->
                          c s ->
                            Thrift.Counter ->
                              Thrift.SendCallback ->
                                Thrift.RecvCallback ->
                                  Thrift.RpcOptions -> Text.Text -> Prelude.IO ()
send_echoWithResponse _proxy _channel _counter _sendCob _recvCob
  _rpcOpts __field__initial
  = do _seqNum <- _counter
       let
         _callMsg
           = LBS.toStrict
               (ByteString.toLazyByteString
                  (_build_echoWithResponse _proxy _seqNum __field__initial))
       Thrift.sendRequest _channel
         (Thrift.Request _callMsg
            (Thrift.setRpcPriority _rpcOpts Thrift.NormalPriority))
         _sendCob
         _recvCob

recv_echoWithResponse ::
                        (Thrift.Protocol p) =>
                        Proxy.Proxy p ->
                          Thrift.Response -> Prelude.Either Exception.SomeException ()
recv_echoWithResponse _proxy (Thrift.Response _response _)
  = Monad.join
      (Arrow.left (Exception.SomeException . Thrift.ProtocolException)
         (Parser.parse (_parse_echoWithResponse _proxy) _response))

_build_echoWithResponse ::
                          Thrift.Protocol p =>
                          Proxy.Proxy p -> Int.Int32 -> Text.Text -> ByteString.Builder
_build_echoWithResponse _proxy _seqNum __field__initial
  = Thrift.genMsgBegin _proxy "echoWithResponse" 1 _seqNum <>
      Thrift.genStruct _proxy
        (Thrift.genField _proxy "initial" (Thrift.getStringType _proxy) 1 0
           (Thrift.genText _proxy __field__initial)
           : [])
      <> Thrift.genMsgEnd _proxy

_parse_echoWithResponse ::
                          Thrift.Protocol p =>
                          Proxy.Proxy p ->
                            Parser.Parser (Prelude.Either Exception.SomeException ())
_parse_echoWithResponse _proxy
  = do Thrift.MsgBegin _name _msgTy _ <- Thrift.parseMsgBegin _proxy
       _result <- case _msgTy of
                    1 -> Prelude.fail
                           "echoWithResponse: expected reply but got function call"
                    2 | _name == "echoWithResponse" ->
                        do let
                             _idMap = HashMap.fromList []
                           _fieldBegin <- Thrift.parseFieldBegin _proxy 0 _idMap
                           case _fieldBegin of
                             Thrift.FieldBegin _type _id _bool -> do case _id of
                                                                       _ -> Prelude.fail
                                                                              (Prelude.unwords
                                                                                 ["unrecognized exception, type:",
                                                                                  Prelude.show
                                                                                    _type,
                                                                                  "field id:",
                                                                                  Prelude.show _id])
                             Thrift.FieldEnd -> Prelude.return (Prelude.Right ())
                      | Prelude.otherwise -> Prelude.fail "reply function does not match"
                    3 -> Prelude.fmap (Prelude.Left . Exception.SomeException)
                           (Thrift.parseStruct _proxy ::
                              Parser.Parser Thrift.ApplicationException)
                    4 -> Prelude.fail
                           "echoWithResponse: expected reply but got oneway function call"
                    _ -> Prelude.fail "echoWithResponse: invalid message type"
       Thrift.parseMsgEnd _proxy
       Prelude.return _result

intStream ::
            (Thrift.Protocol p, Thrift.ClientChannel c,
             (Thrift.<:) s TestBiDiService) =>
            Thrift.ThriftM p c s ()
intStream
  = do Thrift.ThriftEnv _proxy _channel _opts _counter <- Reader.ask
       Trans.lift (intStreamIO _proxy _channel _counter _opts)

intStreamIO ::
              (Thrift.Protocol p, Thrift.ClientChannel c,
               (Thrift.<:) s TestBiDiService) =>
              Proxy.Proxy p ->
                c s -> Thrift.Counter -> Thrift.RpcOptions -> Prelude.IO ()
intStreamIO _proxy _channel _counter _opts
  = do (_handle, _sendCob, _recvCob) <- Thrift.mkCallbacks
                                          (recv_intStream _proxy)
       send_intStream _proxy _channel _counter _sendCob _recvCob _opts
       Thrift.wait _handle

send_intStream ::
                 (Thrift.Protocol p, Thrift.ClientChannel c,
                  (Thrift.<:) s TestBiDiService) =>
                 Proxy.Proxy p ->
                   c s ->
                     Thrift.Counter ->
                       Thrift.SendCallback ->
                         Thrift.RecvCallback -> Thrift.RpcOptions -> Prelude.IO ()
send_intStream _proxy _channel _counter _sendCob _recvCob _rpcOpts
  = do _seqNum <- _counter
       let
         _callMsg
           = LBS.toStrict
               (ByteString.toLazyByteString (_build_intStream _proxy _seqNum))
       Thrift.sendRequest _channel
         (Thrift.Request _callMsg
            (Thrift.setRpcPriority _rpcOpts Thrift.NormalPriority))
         _sendCob
         _recvCob

recv_intStream ::
                 (Thrift.Protocol p) =>
                 Proxy.Proxy p ->
                   Thrift.Response -> Prelude.Either Exception.SomeException ()
recv_intStream _proxy (Thrift.Response _response _)
  = Monad.join
      (Arrow.left (Exception.SomeException . Thrift.ProtocolException)
         (Parser.parse (_parse_intStream _proxy) _response))

_build_intStream ::
                   Thrift.Protocol p =>
                   Proxy.Proxy p -> Int.Int32 -> ByteString.Builder
_build_intStream _proxy _seqNum
  = Thrift.genMsgBegin _proxy "intStream" 1 _seqNum <>
      Thrift.genStruct _proxy []
      <> Thrift.genMsgEnd _proxy

_parse_intStream ::
                   Thrift.Protocol p =>
                   Proxy.Proxy p ->
                     Parser.Parser (Prelude.Either Exception.SomeException ())
_parse_intStream _proxy
  = do Thrift.MsgBegin _name _msgTy _ <- Thrift.parseMsgBegin _proxy
       _result <- case _msgTy of
                    1 -> Prelude.fail "intStream: expected reply but got function call"
                    2 | _name == "intStream" ->
                        do let
                             _idMap = HashMap.fromList []
                           _fieldBegin <- Thrift.parseFieldBegin _proxy 0 _idMap
                           case _fieldBegin of
                             Thrift.FieldBegin _type _id _bool -> do case _id of
                                                                       _ -> Prelude.fail
                                                                              (Prelude.unwords
                                                                                 ["unrecognized exception, type:",
                                                                                  Prelude.show
                                                                                    _type,
                                                                                  "field id:",
                                                                                  Prelude.show _id])
                             Thrift.FieldEnd -> Prelude.return (Prelude.Right ())
                      | Prelude.otherwise -> Prelude.fail "reply function does not match"
                    3 -> Prelude.fmap (Prelude.Left . Exception.SomeException)
                           (Thrift.parseStruct _proxy ::
                              Parser.Parser Thrift.ApplicationException)
                    4 -> Prelude.fail
                           "intStream: expected reply but got oneway function call"
                    _ -> Prelude.fail "intStream: invalid message type"
       Thrift.parseMsgEnd _proxy
       Prelude.return _result

canThrow ::
           (Thrift.Protocol p, Thrift.ClientChannel c,
            (Thrift.<:) s TestBiDiService) =>
           Thrift.ThriftM p c s ()
canThrow
  = do Thrift.ThriftEnv _proxy _channel _opts _counter <- Reader.ask
       Trans.lift (canThrowIO _proxy _channel _counter _opts)

canThrowIO ::
             (Thrift.Protocol p, Thrift.ClientChannel c,
              (Thrift.<:) s TestBiDiService) =>
             Proxy.Proxy p ->
               c s -> Thrift.Counter -> Thrift.RpcOptions -> Prelude.IO ()
canThrowIO _proxy _channel _counter _opts
  = do (_handle, _sendCob, _recvCob) <- Thrift.mkCallbacks
                                          (recv_canThrow _proxy)
       send_canThrow _proxy _channel _counter _sendCob _recvCob _opts
       Thrift.wait _handle

send_canThrow ::
                (Thrift.Protocol p, Thrift.ClientChannel c,
                 (Thrift.<:) s TestBiDiService) =>
                Proxy.Proxy p ->
                  c s ->
                    Thrift.Counter ->
                      Thrift.SendCallback ->
                        Thrift.RecvCallback -> Thrift.RpcOptions -> Prelude.IO ()
send_canThrow _proxy _channel _counter _sendCob _recvCob _rpcOpts
  = do _seqNum <- _counter
       let
         _callMsg
           = LBS.toStrict
               (ByteString.toLazyByteString (_build_canThrow _proxy _seqNum))
       Thrift.sendRequest _channel
         (Thrift.Request _callMsg
            (Thrift.setRpcPriority _rpcOpts Thrift.NormalPriority))
         _sendCob
         _recvCob

recv_canThrow ::
                (Thrift.Protocol p) =>
                Proxy.Proxy p ->
                  Thrift.Response -> Prelude.Either Exception.SomeException ()
recv_canThrow _proxy (Thrift.Response _response _)
  = Monad.join
      (Arrow.left (Exception.SomeException . Thrift.ProtocolException)
         (Parser.parse (_parse_canThrow _proxy) _response))

_build_canThrow ::
                  Thrift.Protocol p =>
                  Proxy.Proxy p -> Int.Int32 -> ByteString.Builder
_build_canThrow _proxy _seqNum
  = Thrift.genMsgBegin _proxy "canThrow" 1 _seqNum <>
      Thrift.genStruct _proxy []
      <> Thrift.genMsgEnd _proxy

_parse_canThrow ::
                  Thrift.Protocol p =>
                  Proxy.Proxy p ->
                    Parser.Parser (Prelude.Either Exception.SomeException ())
_parse_canThrow _proxy
  = do Thrift.MsgBegin _name _msgTy _ <- Thrift.parseMsgBegin _proxy
       _result <- case _msgTy of
                    1 -> Prelude.fail "canThrow: expected reply but got function call"
                    2 | _name == "canThrow" ->
                        do let
                             _idMap = HashMap.fromList [("methodEx", 1)]
                           _fieldBegin <- Thrift.parseFieldBegin _proxy 0 _idMap
                           case _fieldBegin of
                             Thrift.FieldBegin _type _id _bool -> do case _id of
                                                                       1 | _type ==
                                                                             Thrift.getStructType
                                                                               _proxy
                                                                           ->
                                                                           Prelude.fmap
                                                                             (Prelude.Left .
                                                                                Exception.SomeException)
                                                                             (Thrift.parseStruct
                                                                                _proxy
                                                                                ::
                                                                                Parser.Parser
                                                                                  BiDiMethodException)
                                                                       _ -> Prelude.fail
                                                                              (Prelude.unwords
                                                                                 ["unrecognized exception, type:",
                                                                                  Prelude.show
                                                                                    _type,
                                                                                  "field id:",
                                                                                  Prelude.show _id])
                             Thrift.FieldEnd -> Prelude.return (Prelude.Right ())
                      | Prelude.otherwise -> Prelude.fail "reply function does not match"
                    3 -> Prelude.fmap (Prelude.Left . Exception.SomeException)
                           (Thrift.parseStruct _proxy ::
                              Parser.Parser Thrift.ApplicationException)
                    4 -> Prelude.fail
                           "canThrow: expected reply but got oneway function call"
                    _ -> Prelude.fail "canThrow: invalid message type"
       Thrift.parseMsgEnd _proxy
       Prelude.return _result