-----------------------------------------------------------------
-- Autogenerated by Thrift
--
-- DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
--  @generated
-----------------------------------------------------------------
{-# LANGUAGE OverloadedStrings #-}
{-# LANGUAGE BangPatterns #-}
{-# OPTIONS_GHC -fno-warn-unused-imports#-}
{-# OPTIONS_GHC -fno-warn-overlapping-patterns#-}
{-# OPTIONS_GHC -fno-warn-incomplete-patterns#-}
{-# OPTIONS_GHC -fno-warn-incomplete-uni-patterns#-}
{-# OPTIONS_GHC -fno-warn-incomplete-record-updates#-}
{-# LANGUAGE GeneralizedNewtypeDeriving #-}
module C.Types
       (FirstAnnotation(FirstAnnotation, firstAnnotation_name,
                        firstAnnotation_count),
        SecondAnnotation(SecondAnnotation, secondAnnotation_total,
                         secondAnnotation_recurse, secondAnnotation_either),
        UnionAnnotation(UnionAnnotation_EMPTY, UnionAnnotation_left,
                        UnionAnnotation_right),
        Annotated_string, MyStruct(MyStruct, myStruct_tag),
        MyException(MyException, myException_message),
        MyUnion(MyUnion_EMPTY, MyUnion_int_value, MyUnion_string_value),
        MyEnum(MyEnum_UNKNOWN, MyEnum_FIRST, MyEnum__UNKNOWN), myConst)
       where
import qualified Control.DeepSeq as DeepSeq
import qualified Control.Exception as Exception
import qualified Control.Monad as Monad
import qualified Control.Monad.ST.Trans as ST
import qualified Control.Monad.Trans.Class as Trans
import qualified Data.Aeson as Aeson
import qualified Data.Aeson.Types as Aeson
import qualified Data.Default as Default
import qualified Data.Function as Function
import qualified Data.HashMap.Strict as HashMap
import qualified Data.Hashable as Hashable
import qualified Data.Int as Int
import qualified Data.List as List
import qualified Data.Map.Strict as Map
import qualified Data.Ord as Ord
import qualified Data.Text as Text
import qualified Data.Text.Encoding as Text
import qualified Facebook.Thrift.Annotation.Thrift.Thrift.Types
       as Facebook.Thrift.Annotation.Thrift.Thrift
import qualified GHC.Magic as GHC
import qualified Prelude as Prelude
import qualified Thrift.Binary.Parser as Parser
import qualified Thrift.CodegenTypesOnly as Thrift
import Control.Applicative ((<|>), (*>), (<*))
import Data.Aeson ((.:), (.:?), (.=), (.!=))
import Data.Aeson ((.:), (.=))
import Data.Monoid ((<>))
import Prelude ((.), (++), (>), (==))
import Prelude ((.), (<$>), (<*>), (>>=), (==), (++))
import Prelude ((.), (<$>), (<*>), (>>=), (==), (/=), (<), (++))

data FirstAnnotation = FirstAnnotation{firstAnnotation_name ::
                                       Text.Text,
                                       firstAnnotation_count :: Int.Int64}
                       deriving (Prelude.Eq, Prelude.Show, Prelude.Ord)

instance Aeson.ToJSON FirstAnnotation where
  toJSON (FirstAnnotation __field__name __field__count)
    = Aeson.object
        ("name" .= __field__name :
           "count" .= __field__count : Prelude.mempty)

instance Thrift.ThriftStruct FirstAnnotation where
  buildStruct _proxy (FirstAnnotation __field__name __field__count)
    = Thrift.genStruct _proxy
        (Thrift.genField _proxy "name" (Thrift.getStringType _proxy) 1 0
           (Thrift.genText _proxy __field__name)
           :
           Thrift.genFieldPrim _proxy "count" (Thrift.getI64Type _proxy) 2 1
             (Thrift.genI64Prim _proxy)
             __field__count
             : [])
  parseStruct _proxy
    = ST.runSTT
        (do Prelude.return ()
            __field__name <- ST.newSTRef ""
            __field__count <- ST.newSTRef 1
            let
              _parse _lastId
                = do _fieldBegin <- Trans.lift
                                      (Thrift.parseFieldBegin _proxy _lastId _idMap)
                     case _fieldBegin of
                       Thrift.FieldBegin _type _id _bool -> do case _id of
                                                                 1 | _type ==
                                                                       Thrift.getStringType _proxy
                                                                     ->
                                                                     do !_val <- Trans.lift
                                                                                   (Thrift.parseText
                                                                                      _proxy)
                                                                        ST.writeSTRef __field__name
                                                                          _val
                                                                 2 | _type ==
                                                                       Thrift.getI64Type _proxy
                                                                     ->
                                                                     do !_val <- Trans.lift
                                                                                   (Thrift.parseI64
                                                                                      _proxy)
                                                                        ST.writeSTRef __field__count
                                                                          _val
                                                                 _ -> Trans.lift
                                                                        (Thrift.parseSkip _proxy
                                                                           _type
                                                                           (Prelude.Just _bool))
                                                               _parse _id
                       Thrift.FieldEnd -> do !__val__name <- ST.readSTRef __field__name
                                             !__val__count <- ST.readSTRef __field__count
                                             Prelude.pure (FirstAnnotation __val__name __val__count)
              _idMap = HashMap.fromList [("name", 1), ("count", 2)]
            _parse 0)

instance DeepSeq.NFData FirstAnnotation where
  rnf (FirstAnnotation __field__name __field__count)
    = DeepSeq.rnf __field__name `Prelude.seq`
        DeepSeq.rnf __field__count `Prelude.seq` ()

instance Default.Default FirstAnnotation where
  def = FirstAnnotation "" 1

instance Hashable.Hashable FirstAnnotation where
  hashWithSalt __salt (FirstAnnotation _name _count)
    = Hashable.hashWithSalt (Hashable.hashWithSalt __salt _name) _count

data SecondAnnotation = SecondAnnotation{secondAnnotation_total ::
                                         Int.Int64,
                                         secondAnnotation_recurse :: SecondAnnotation,
                                         secondAnnotation_either :: UnionAnnotation}
                        deriving (Prelude.Eq, Prelude.Show, Prelude.Ord)

instance Aeson.ToJSON SecondAnnotation where
  toJSON
    (SecondAnnotation __field__total __field__recurse __field__either)
    = Aeson.object
        ("total" .= __field__total :
           "recurse" .= __field__recurse :
             "either" .= __field__either : Prelude.mempty)

instance Thrift.ThriftStruct SecondAnnotation where
  buildStruct _proxy
    (SecondAnnotation __field__total __field__recurse __field__either)
    = Thrift.genStruct _proxy
        (Thrift.genFieldPrim _proxy "total" (Thrift.getI64Type _proxy) 2 0
           (Thrift.genI64Prim _proxy)
           __field__total
           :
           Thrift.genField _proxy "recurse" (Thrift.getStructType _proxy) 3 2
             (Thrift.buildStruct _proxy __field__recurse)
             :
             Thrift.genField _proxy "either" (Thrift.getStructType _proxy) 4 3
               (Thrift.buildStruct _proxy __field__either)
               : [])
  parseStruct _proxy
    = ST.runSTT
        (do Prelude.return ()
            __field__total <- ST.newSTRef 0
            __field__recurse <- ST.newSTRef Default.def
            __field__either <- ST.newSTRef Default.def
            let
              _parse _lastId
                = do _fieldBegin <- Trans.lift
                                      (Thrift.parseFieldBegin _proxy _lastId _idMap)
                     case _fieldBegin of
                       Thrift.FieldBegin _type _id _bool -> do case _id of
                                                                 2 | _type ==
                                                                       Thrift.getI64Type _proxy
                                                                     ->
                                                                     do !_val <- Trans.lift
                                                                                   (Thrift.parseI64
                                                                                      _proxy)
                                                                        ST.writeSTRef __field__total
                                                                          _val
                                                                 3 | _type ==
                                                                       Thrift.getStructType _proxy
                                                                     ->
                                                                     do !_val <- Trans.lift
                                                                                   (Thrift.parseStruct
                                                                                      _proxy)
                                                                        ST.writeSTRef
                                                                          __field__recurse
                                                                          _val
                                                                 4 | _type ==
                                                                       Thrift.getStructType _proxy
                                                                     ->
                                                                     do !_val <- Trans.lift
                                                                                   (Thrift.parseStruct
                                                                                      _proxy)
                                                                        ST.writeSTRef
                                                                          __field__either
                                                                          _val
                                                                 _ -> Trans.lift
                                                                        (Thrift.parseSkip _proxy
                                                                           _type
                                                                           (Prelude.Just _bool))
                                                               _parse _id
                       Thrift.FieldEnd -> do !__val__total <- ST.readSTRef __field__total
                                             !__val__recurse <- ST.readSTRef __field__recurse
                                             !__val__either <- ST.readSTRef __field__either
                                             Prelude.pure
                                               (SecondAnnotation __val__total __val__recurse
                                                  __val__either)
              _idMap
                = HashMap.fromList [("total", 2), ("recurse", 3), ("either", 4)]
            _parse 0)

instance DeepSeq.NFData SecondAnnotation where
  rnf
    (SecondAnnotation __field__total __field__recurse __field__either)
    = DeepSeq.rnf __field__total `Prelude.seq`
        DeepSeq.rnf __field__recurse `Prelude.seq`
          DeepSeq.rnf __field__either `Prelude.seq` ()

instance Default.Default SecondAnnotation where
  def = SecondAnnotation 0 Default.def Default.def

instance Hashable.Hashable SecondAnnotation where
  hashWithSalt __salt (SecondAnnotation _total _recurse _either)
    = Hashable.hashWithSalt
        (Hashable.hashWithSalt (Hashable.hashWithSalt __salt _total)
           _recurse)
        _either

data UnionAnnotation = UnionAnnotation_left Int.Int64
                     | UnionAnnotation_right Int.Int64
                     | UnionAnnotation_EMPTY
                       deriving (Prelude.Eq, Prelude.Show, Prelude.Ord)

instance Aeson.ToJSON UnionAnnotation where
  toJSON (UnionAnnotation_left __left)
    = Aeson.object ["left" .= __left]
  toJSON (UnionAnnotation_right __right)
    = Aeson.object ["right" .= __right]
  toJSON UnionAnnotation_EMPTY = Aeson.object []

instance Thrift.ThriftStruct UnionAnnotation where
  buildStruct _proxy (UnionAnnotation_left __left)
    = Thrift.genStruct _proxy
        [Thrift.genFieldPrim _proxy "left" (Thrift.getI64Type _proxy) 2 0
           (Thrift.genI64Prim _proxy)
           __left]
  buildStruct _proxy (UnionAnnotation_right __right)
    = Thrift.genStruct _proxy
        [Thrift.genFieldPrim _proxy "right" (Thrift.getI64Type _proxy) 3 0
           (Thrift.genI64Prim _proxy)
           __right]
  buildStruct _proxy UnionAnnotation_EMPTY
    = Thrift.genStruct _proxy []
  parseStruct _proxy
    = do _fieldBegin <- Thrift.parseFieldBegin _proxy 0 _idMap
         case _fieldBegin of
           Thrift.FieldBegin _type _id _bool -> do case _id of
                                                     2 | _type == Thrift.getI64Type _proxy ->
                                                         do _val <- Thrift.parseI64 _proxy
                                                            Thrift.parseStop _proxy
                                                            Prelude.return
                                                              (UnionAnnotation_left _val)
                                                     3 | _type == Thrift.getI64Type _proxy ->
                                                         do _val <- Thrift.parseI64 _proxy
                                                            Thrift.parseStop _proxy
                                                            Prelude.return
                                                              (UnionAnnotation_right _val)
                                                     _ -> do Thrift.parseSkip _proxy _type
                                                               Prelude.Nothing
                                                             Thrift.parseStop _proxy
                                                             Prelude.return UnionAnnotation_EMPTY
           Thrift.FieldEnd -> Prelude.return UnionAnnotation_EMPTY
    where
      _idMap = HashMap.fromList [("left", 2), ("right", 3)]

instance DeepSeq.NFData UnionAnnotation where
  rnf (UnionAnnotation_left __left) = DeepSeq.rnf __left
  rnf (UnionAnnotation_right __right) = DeepSeq.rnf __right
  rnf UnionAnnotation_EMPTY = ()

instance Default.Default UnionAnnotation where
  def = UnionAnnotation_EMPTY

instance Hashable.Hashable UnionAnnotation where
  hashWithSalt __salt (UnionAnnotation_left _left)
    = Hashable.hashWithSalt __salt (Hashable.hashWithSalt 2 _left)
  hashWithSalt __salt (UnionAnnotation_right _right)
    = Hashable.hashWithSalt __salt (Hashable.hashWithSalt 3 _right)
  hashWithSalt __salt UnionAnnotation_EMPTY
    = Hashable.hashWithSalt __salt (0 :: Prelude.Int)

type Annotated_string = Text.Text

newtype MyStruct = MyStruct{myStruct_tag :: Annotated_string}
                   deriving (Prelude.Eq, Prelude.Show, Prelude.Ord)

instance Aeson.ToJSON MyStruct where
  toJSON (MyStruct __field__tag)
    = Aeson.object ("tag" .= __field__tag : Prelude.mempty)

instance Thrift.ThriftStruct MyStruct where
  buildStruct _proxy (MyStruct __field__tag)
    = Thrift.genStruct _proxy
        (Thrift.genField _proxy "tag" (Thrift.getStringType _proxy) 5 0
           (Thrift.genText _proxy __field__tag)
           : [])
  parseStruct _proxy
    = ST.runSTT
        (do Prelude.return ()
            __field__tag <- ST.newSTRef ""
            let
              _parse _lastId
                = do _fieldBegin <- Trans.lift
                                      (Thrift.parseFieldBegin _proxy _lastId _idMap)
                     case _fieldBegin of
                       Thrift.FieldBegin _type _id _bool -> do case _id of
                                                                 5 | _type ==
                                                                       Thrift.getStringType _proxy
                                                                     ->
                                                                     do !_val <- Trans.lift
                                                                                   (Thrift.parseText
                                                                                      _proxy)
                                                                        ST.writeSTRef __field__tag
                                                                          _val
                                                                 _ -> Trans.lift
                                                                        (Thrift.parseSkip _proxy
                                                                           _type
                                                                           (Prelude.Just _bool))
                                                               _parse _id
                       Thrift.FieldEnd -> do !__val__tag <- ST.readSTRef __field__tag
                                             Prelude.pure (MyStruct __val__tag)
              _idMap = HashMap.fromList [("tag", 5)]
            _parse 0)

instance DeepSeq.NFData MyStruct where
  rnf (MyStruct __field__tag)
    = DeepSeq.rnf __field__tag `Prelude.seq` ()

instance Default.Default MyStruct where
  def = MyStruct ""

instance Hashable.Hashable MyStruct where
  hashWithSalt __salt (MyStruct _tag)
    = Hashable.hashWithSalt __salt _tag

newtype MyException = MyException{myException_message :: Text.Text}
                      deriving (Prelude.Eq, Prelude.Show, Prelude.Ord)

instance Aeson.ToJSON MyException where
  toJSON (MyException __field__message)
    = Aeson.object ("message" .= __field__message : Prelude.mempty)

instance Thrift.ThriftStruct MyException where
  buildStruct _proxy (MyException __field__message)
    = Thrift.genStruct _proxy
        (Thrift.genField _proxy "message" (Thrift.getStringType _proxy) 1 0
           (Thrift.genText _proxy __field__message)
           : [])
  parseStruct _proxy
    = ST.runSTT
        (do Prelude.return ()
            __field__message <- ST.newSTRef ""
            let
              _parse _lastId
                = do _fieldBegin <- Trans.lift
                                      (Thrift.parseFieldBegin _proxy _lastId _idMap)
                     case _fieldBegin of
                       Thrift.FieldBegin _type _id _bool -> do case _id of
                                                                 1 | _type ==
                                                                       Thrift.getStringType _proxy
                                                                     ->
                                                                     do !_val <- Trans.lift
                                                                                   (Thrift.parseText
                                                                                      _proxy)
                                                                        ST.writeSTRef
                                                                          __field__message
                                                                          _val
                                                                 _ -> Trans.lift
                                                                        (Thrift.parseSkip _proxy
                                                                           _type
                                                                           (Prelude.Just _bool))
                                                               _parse _id
                       Thrift.FieldEnd -> do !__val__message <- ST.readSTRef
                                                                  __field__message
                                             Prelude.pure (MyException __val__message)
              _idMap = HashMap.fromList [("message", 1)]
            _parse 0)

instance DeepSeq.NFData MyException where
  rnf (MyException __field__message)
    = DeepSeq.rnf __field__message `Prelude.seq` ()

instance Default.Default MyException where
  def = MyException ""

instance Hashable.Hashable MyException where
  hashWithSalt __salt (MyException _message)
    = Hashable.hashWithSalt __salt _message

instance Exception.Exception MyException

data MyUnion = MyUnion_int_value Int.Int64
             | MyUnion_string_value Text.Text
             | MyUnion_EMPTY
               deriving (Prelude.Eq, Prelude.Show, Prelude.Ord)

instance Aeson.ToJSON MyUnion where
  toJSON (MyUnion_int_value __int_value)
    = Aeson.object ["int_value" .= __int_value]
  toJSON (MyUnion_string_value __string_value)
    = Aeson.object ["string_value" .= __string_value]
  toJSON MyUnion_EMPTY = Aeson.object []

instance Thrift.ThriftStruct MyUnion where
  buildStruct _proxy (MyUnion_int_value __int_value)
    = Thrift.genStruct _proxy
        [Thrift.genFieldPrim _proxy "int_value" (Thrift.getI64Type _proxy)
           1
           0
           (Thrift.genI64Prim _proxy)
           __int_value]
  buildStruct _proxy (MyUnion_string_value __string_value)
    = Thrift.genStruct _proxy
        [Thrift.genField _proxy "string_value"
           (Thrift.getStringType _proxy)
           2
           0
           (Thrift.genText _proxy __string_value)]
  buildStruct _proxy MyUnion_EMPTY = Thrift.genStruct _proxy []
  parseStruct _proxy
    = do _fieldBegin <- Thrift.parseFieldBegin _proxy 0 _idMap
         case _fieldBegin of
           Thrift.FieldBegin _type _id _bool -> do case _id of
                                                     1 | _type == Thrift.getI64Type _proxy ->
                                                         do _val <- Thrift.parseI64 _proxy
                                                            Thrift.parseStop _proxy
                                                            Prelude.return (MyUnion_int_value _val)
                                                     2 | _type == Thrift.getStringType _proxy ->
                                                         do _val <- Thrift.parseText _proxy
                                                            Thrift.parseStop _proxy
                                                            Prelude.return
                                                              (MyUnion_string_value _val)
                                                     _ -> do Thrift.parseSkip _proxy _type
                                                               Prelude.Nothing
                                                             Thrift.parseStop _proxy
                                                             Prelude.return MyUnion_EMPTY
           Thrift.FieldEnd -> Prelude.return MyUnion_EMPTY
    where
      _idMap = HashMap.fromList [("int_value", 1), ("string_value", 2)]

instance DeepSeq.NFData MyUnion where
  rnf (MyUnion_int_value __int_value) = DeepSeq.rnf __int_value
  rnf (MyUnion_string_value __string_value)
    = DeepSeq.rnf __string_value
  rnf MyUnion_EMPTY = ()

instance Default.Default MyUnion where
  def = MyUnion_EMPTY

instance Hashable.Hashable MyUnion where
  hashWithSalt __salt (MyUnion_int_value _int_value)
    = Hashable.hashWithSalt __salt (Hashable.hashWithSalt 1 _int_value)
  hashWithSalt __salt (MyUnion_string_value _string_value)
    = Hashable.hashWithSalt __salt
        (Hashable.hashWithSalt 2 _string_value)
  hashWithSalt __salt MyUnion_EMPTY
    = Hashable.hashWithSalt __salt (0 :: Prelude.Int)

data MyEnum = MyEnum_UNKNOWN
            | MyEnum_FIRST
            | MyEnum__UNKNOWN Prelude.Int
              deriving (Prelude.Eq, Prelude.Show, Prelude.Ord)

instance Aeson.ToJSON MyEnum where
  toJSON = Aeson.toJSON . Thrift.fromThriftEnum

instance DeepSeq.NFData MyEnum where
  rnf __MyEnum = Prelude.seq __MyEnum ()

instance Default.Default MyEnum where
  def = MyEnum_UNKNOWN

instance Hashable.Hashable MyEnum where
  hashWithSalt _salt _val
    = Hashable.hashWithSalt _salt (Thrift.fromThriftEnum _val)

instance Thrift.ThriftEnum MyEnum where
  toThriftEnum 0 = MyEnum_UNKNOWN
  toThriftEnum 1 = MyEnum_FIRST
  toThriftEnum val = MyEnum__UNKNOWN val
  fromThriftEnum MyEnum_UNKNOWN = 0
  fromThriftEnum MyEnum_FIRST = 1
  fromThriftEnum (MyEnum__UNKNOWN val) = val
  allThriftEnumValues = [MyEnum_UNKNOWN, MyEnum_FIRST]
  toThriftEnumEither 0 = Prelude.Right MyEnum_UNKNOWN
  toThriftEnumEither 1 = Prelude.Right MyEnum_FIRST
  toThriftEnumEither val
    = Prelude.Left
        ("toThriftEnumEither: not a valid identifier for enum MyEnum: " ++
           Prelude.show val)

myConst :: Map.Map Text.Text Text.Text
myConst = Map.fromList [("ENUMERATOR", "value")]