-----------------------------------------------------------------
-- Autogenerated by Thrift
--
-- DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
--  @generated
-----------------------------------------------------------------
{-# LANGUAGE OverloadedStrings #-}
{-# LANGUAGE BangPatterns #-}
{-# OPTIONS_GHC -fno-warn-unused-imports#-}
{-# OPTIONS_GHC -fno-warn-overlapping-patterns#-}
{-# OPTIONS_GHC -fno-warn-incomplete-patterns#-}
{-# OPTIONS_GHC -fno-warn-incomplete-uni-patterns#-}
{-# OPTIONS_GHC -fno-warn-incomplete-record-updates#-}
{-# LANGUAGE GeneralizedNewtypeDeriving #-}
module Facebook.Thrift.Annotation.Haskell.Haskell.Types
       (Type(Type, type_name), Lazy(Lazy), Strict(Strict), Hidden(Hidden),
        Newtype(Newtype), NonEmpty(NonEmpty), NoUnknown(NoUnknown),
        PseudoEnum(PseudoEnum, pseudoEnum_value),
        Prefix(Prefix, prefix_name))
       where
import qualified Control.DeepSeq as DeepSeq
import qualified Control.Monad as Monad
import qualified Control.Monad.ST.Trans as ST
import qualified Control.Monad.Trans.Class as Trans
import qualified Data.Aeson as Aeson
import qualified Data.Aeson.Types as Aeson
import qualified Data.Default as Default
import qualified Data.HashMap.Strict as HashMap
import qualified Data.Hashable as Hashable
import qualified Data.List as List
import qualified Data.Ord as Ord
import qualified Data.Text as Text
import qualified Data.Text.Encoding as Text
import qualified Facebook.Thrift.Annotation.Thrift.Thrift.Types
       as Facebook.Thrift.Annotation.Thrift.Thrift
import qualified Prelude as Prelude
import qualified Scope.Types as Scope
import qualified Thrift.Binary.Parser as Parser
import qualified Thrift.CodegenTypesOnly as Thrift
import Control.Applicative ((<|>), (*>), (<*))
import Data.Aeson ((.:), (.:?), (.=), (.!=))
import Data.Monoid ((<>))
import Prelude ((.), (<$>), (<*>), (>>=), (==), (/=), (<), (++))

newtype Type = Type{type_name :: Text.Text}
               deriving (Prelude.Eq, Prelude.Show, Prelude.Ord)

instance Aeson.ToJSON Type where
  toJSON (Type __field__name)
    = Aeson.object ("name" .= __field__name : Prelude.mempty)

instance Thrift.ThriftStruct Type where
  buildStruct _proxy (Type __field__name)
    = Thrift.genStruct _proxy
        (Thrift.genField _proxy "name" (Thrift.getStringType _proxy) 1 0
           (Thrift.genText _proxy __field__name)
           : [])
  parseStruct _proxy
    = ST.runSTT
        (do Prelude.return ()
            __field__name <- ST.newSTRef ""
            let
              _parse _lastId
                = do _fieldBegin <- Trans.lift
                                      (Thrift.parseFieldBegin _proxy _lastId _idMap)
                     case _fieldBegin of
                       Thrift.FieldBegin _type _id _bool -> do case _id of
                                                                 1 | _type ==
                                                                       Thrift.getStringType _proxy
                                                                     ->
                                                                     do !_val <- Trans.lift
                                                                                   (Thrift.parseText
                                                                                      _proxy)
                                                                        ST.writeSTRef __field__name
                                                                          _val
                                                                 _ -> Trans.lift
                                                                        (Thrift.parseSkip _proxy
                                                                           _type
                                                                           (Prelude.Just _bool))
                                                               _parse _id
                       Thrift.FieldEnd -> do !__val__name <- ST.readSTRef __field__name
                                             Prelude.pure (Type __val__name)
              _idMap = HashMap.fromList [("name", 1)]
            _parse 0)

instance DeepSeq.NFData Type where
  rnf (Type __field__name)
    = DeepSeq.rnf __field__name `Prelude.seq` ()

instance Default.Default Type where
  def = Type ""

instance Hashable.Hashable Type where
  hashWithSalt __salt (Type _name)
    = Hashable.hashWithSalt __salt _name

data Lazy = Lazy{}
            deriving (Prelude.Eq, Prelude.Show, Prelude.Ord)

instance Aeson.ToJSON Lazy where
  toJSON Lazy = Aeson.object Prelude.mempty

instance Thrift.ThriftStruct Lazy where
  buildStruct _proxy Lazy = Thrift.genStruct _proxy []
  parseStruct _proxy
    = ST.runSTT
        (do Prelude.return ()
            let
              _parse _lastId
                = do _fieldBegin <- Trans.lift
                                      (Thrift.parseFieldBegin _proxy _lastId _idMap)
                     case _fieldBegin of
                       Thrift.FieldBegin _type _id _bool -> do case _id of
                                                                 _ -> Trans.lift
                                                                        (Thrift.parseSkip _proxy
                                                                           _type
                                                                           (Prelude.Just _bool))
                                                               _parse _id
                       Thrift.FieldEnd -> do Prelude.pure (Lazy)
              _idMap = HashMap.fromList []
            _parse 0)

instance DeepSeq.NFData Lazy where
  rnf Lazy = ()

instance Default.Default Lazy where
  def = Lazy

instance Hashable.Hashable Lazy where
  hashWithSalt __salt Lazy = __salt

data Strict = Strict{}
              deriving (Prelude.Eq, Prelude.Show, Prelude.Ord)

instance Aeson.ToJSON Strict where
  toJSON Strict = Aeson.object Prelude.mempty

instance Thrift.ThriftStruct Strict where
  buildStruct _proxy Strict = Thrift.genStruct _proxy []
  parseStruct _proxy
    = ST.runSTT
        (do Prelude.return ()
            let
              _parse _lastId
                = do _fieldBegin <- Trans.lift
                                      (Thrift.parseFieldBegin _proxy _lastId _idMap)
                     case _fieldBegin of
                       Thrift.FieldBegin _type _id _bool -> do case _id of
                                                                 _ -> Trans.lift
                                                                        (Thrift.parseSkip _proxy
                                                                           _type
                                                                           (Prelude.Just _bool))
                                                               _parse _id
                       Thrift.FieldEnd -> do Prelude.pure (Strict)
              _idMap = HashMap.fromList []
            _parse 0)

instance DeepSeq.NFData Strict where
  rnf Strict = ()

instance Default.Default Strict where
  def = Strict

instance Hashable.Hashable Strict where
  hashWithSalt __salt Strict = __salt

data Hidden = Hidden{}
              deriving (Prelude.Eq, Prelude.Show, Prelude.Ord)

instance Aeson.ToJSON Hidden where
  toJSON Hidden = Aeson.object Prelude.mempty

instance Thrift.ThriftStruct Hidden where
  buildStruct _proxy Hidden = Thrift.genStruct _proxy []
  parseStruct _proxy
    = ST.runSTT
        (do Prelude.return ()
            let
              _parse _lastId
                = do _fieldBegin <- Trans.lift
                                      (Thrift.parseFieldBegin _proxy _lastId _idMap)
                     case _fieldBegin of
                       Thrift.FieldBegin _type _id _bool -> do case _id of
                                                                 _ -> Trans.lift
                                                                        (Thrift.parseSkip _proxy
                                                                           _type
                                                                           (Prelude.Just _bool))
                                                               _parse _id
                       Thrift.FieldEnd -> do Prelude.pure (Hidden)
              _idMap = HashMap.fromList []
            _parse 0)

instance DeepSeq.NFData Hidden where
  rnf Hidden = ()

instance Default.Default Hidden where
  def = Hidden

instance Hashable.Hashable Hidden where
  hashWithSalt __salt Hidden = __salt

data Newtype = Newtype{}
               deriving (Prelude.Eq, Prelude.Show, Prelude.Ord)

instance Aeson.ToJSON Newtype where
  toJSON Newtype = Aeson.object Prelude.mempty

instance Thrift.ThriftStruct Newtype where
  buildStruct _proxy Newtype = Thrift.genStruct _proxy []
  parseStruct _proxy
    = ST.runSTT
        (do Prelude.return ()
            let
              _parse _lastId
                = do _fieldBegin <- Trans.lift
                                      (Thrift.parseFieldBegin _proxy _lastId _idMap)
                     case _fieldBegin of
                       Thrift.FieldBegin _type _id _bool -> do case _id of
                                                                 _ -> Trans.lift
                                                                        (Thrift.parseSkip _proxy
                                                                           _type
                                                                           (Prelude.Just _bool))
                                                               _parse _id
                       Thrift.FieldEnd -> do Prelude.pure (Newtype)
              _idMap = HashMap.fromList []
            _parse 0)

instance DeepSeq.NFData Newtype where
  rnf Newtype = ()

instance Default.Default Newtype where
  def = Newtype

instance Hashable.Hashable Newtype where
  hashWithSalt __salt Newtype = __salt

data NonEmpty = NonEmpty{}
                deriving (Prelude.Eq, Prelude.Show, Prelude.Ord)

instance Aeson.ToJSON NonEmpty where
  toJSON NonEmpty = Aeson.object Prelude.mempty

instance Thrift.ThriftStruct NonEmpty where
  buildStruct _proxy NonEmpty = Thrift.genStruct _proxy []
  parseStruct _proxy
    = ST.runSTT
        (do Prelude.return ()
            let
              _parse _lastId
                = do _fieldBegin <- Trans.lift
                                      (Thrift.parseFieldBegin _proxy _lastId _idMap)
                     case _fieldBegin of
                       Thrift.FieldBegin _type _id _bool -> do case _id of
                                                                 _ -> Trans.lift
                                                                        (Thrift.parseSkip _proxy
                                                                           _type
                                                                           (Prelude.Just _bool))
                                                               _parse _id
                       Thrift.FieldEnd -> do Prelude.pure (NonEmpty)
              _idMap = HashMap.fromList []
            _parse 0)

instance DeepSeq.NFData NonEmpty where
  rnf NonEmpty = ()

instance Default.Default NonEmpty where
  def = NonEmpty

instance Hashable.Hashable NonEmpty where
  hashWithSalt __salt NonEmpty = __salt

data NoUnknown = NoUnknown{}
                 deriving (Prelude.Eq, Prelude.Show, Prelude.Ord)

instance Aeson.ToJSON NoUnknown where
  toJSON NoUnknown = Aeson.object Prelude.mempty

instance Thrift.ThriftStruct NoUnknown where
  buildStruct _proxy NoUnknown = Thrift.genStruct _proxy []
  parseStruct _proxy
    = ST.runSTT
        (do Prelude.return ()
            let
              _parse _lastId
                = do _fieldBegin <- Trans.lift
                                      (Thrift.parseFieldBegin _proxy _lastId _idMap)
                     case _fieldBegin of
                       Thrift.FieldBegin _type _id _bool -> do case _id of
                                                                 _ -> Trans.lift
                                                                        (Thrift.parseSkip _proxy
                                                                           _type
                                                                           (Prelude.Just _bool))
                                                               _parse _id
                       Thrift.FieldEnd -> do Prelude.pure (NoUnknown)
              _idMap = HashMap.fromList []
            _parse 0)

instance DeepSeq.NFData NoUnknown where
  rnf NoUnknown = ()

instance Default.Default NoUnknown where
  def = NoUnknown

instance Hashable.Hashable NoUnknown where
  hashWithSalt __salt NoUnknown = __salt

newtype PseudoEnum = PseudoEnum{pseudoEnum_value :: Text.Text}
                     deriving (Prelude.Eq, Prelude.Show, Prelude.Ord)

instance Aeson.ToJSON PseudoEnum where
  toJSON (PseudoEnum __field__value)
    = Aeson.object ("value" .= __field__value : Prelude.mempty)

instance Thrift.ThriftStruct PseudoEnum where
  buildStruct _proxy (PseudoEnum __field__value)
    = Thrift.genStruct _proxy
        (Thrift.genField _proxy "value" (Thrift.getStringType _proxy) 1 0
           (Thrift.genText _proxy __field__value)
           : [])
  parseStruct _proxy
    = ST.runSTT
        (do Prelude.return ()
            __field__value <- ST.newSTRef ""
            let
              _parse _lastId
                = do _fieldBegin <- Trans.lift
                                      (Thrift.parseFieldBegin _proxy _lastId _idMap)
                     case _fieldBegin of
                       Thrift.FieldBegin _type _id _bool -> do case _id of
                                                                 1 | _type ==
                                                                       Thrift.getStringType _proxy
                                                                     ->
                                                                     do !_val <- Trans.lift
                                                                                   (Thrift.parseText
                                                                                      _proxy)
                                                                        ST.writeSTRef __field__value
                                                                          _val
                                                                 _ -> Trans.lift
                                                                        (Thrift.parseSkip _proxy
                                                                           _type
                                                                           (Prelude.Just _bool))
                                                               _parse _id
                       Thrift.FieldEnd -> do !__val__value <- ST.readSTRef __field__value
                                             Prelude.pure (PseudoEnum __val__value)
              _idMap = HashMap.fromList [("value", 1)]
            _parse 0)

instance DeepSeq.NFData PseudoEnum where
  rnf (PseudoEnum __field__value)
    = DeepSeq.rnf __field__value `Prelude.seq` ()

instance Default.Default PseudoEnum where
  def = PseudoEnum ""

instance Hashable.Hashable PseudoEnum where
  hashWithSalt __salt (PseudoEnum _value)
    = Hashable.hashWithSalt __salt _value

newtype Prefix = Prefix{prefix_name :: Text.Text}
                 deriving (Prelude.Eq, Prelude.Show, Prelude.Ord)

instance Aeson.ToJSON Prefix where
  toJSON (Prefix __field__name)
    = Aeson.object ("name" .= __field__name : Prelude.mempty)

instance Thrift.ThriftStruct Prefix where
  buildStruct _proxy (Prefix __field__name)
    = Thrift.genStruct _proxy
        (Thrift.genField _proxy "name" (Thrift.getStringType _proxy) 1 0
           (Thrift.genText _proxy __field__name)
           : [])
  parseStruct _proxy
    = ST.runSTT
        (do Prelude.return ()
            __field__name <- ST.newSTRef ""
            let
              _parse _lastId
                = do _fieldBegin <- Trans.lift
                                      (Thrift.parseFieldBegin _proxy _lastId _idMap)
                     case _fieldBegin of
                       Thrift.FieldBegin _type _id _bool -> do case _id of
                                                                 1 | _type ==
                                                                       Thrift.getStringType _proxy
                                                                     ->
                                                                     do !_val <- Trans.lift
                                                                                   (Thrift.parseText
                                                                                      _proxy)
                                                                        ST.writeSTRef __field__name
                                                                          _val
                                                                 _ -> Trans.lift
                                                                        (Thrift.parseSkip _proxy
                                                                           _type
                                                                           (Prelude.Just _bool))
                                                               _parse _id
                       Thrift.FieldEnd -> do !__val__name <- ST.readSTRef __field__name
                                             Prelude.pure (Prefix __val__name)
              _idMap = HashMap.fromList [("name", 1)]
            _parse 0)

instance DeepSeq.NFData Prefix where
  rnf (Prefix __field__name)
    = DeepSeq.rnf __field__name `Prelude.seq` ()

instance Default.Default Prefix where
  def = Prefix ""

instance Hashable.Hashable Prefix where
  hashWithSalt __salt (Prefix _name)
    = Hashable.hashWithSalt __salt _name