-----------------------------------------------------------------
-- Autogenerated by Thrift
--
-- DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
--  @generated
-----------------------------------------------------------------
{-# LANGUAGE OverloadedStrings #-}
{-# LANGUAGE BangPatterns #-}
{-# OPTIONS_GHC -fno-warn-unused-imports#-}
{-# OPTIONS_GHC -fno-warn-overlapping-patterns#-}
{-# OPTIONS_GHC -fno-warn-incomplete-patterns#-}
{-# OPTIONS_GHC -fno-warn-incomplete-uni-patterns#-}
{-# OPTIONS_GHC -fno-warn-incomplete-record-updates#-}
{-# LANGUAGE GeneralizedNewtypeDeriving #-}
module Bidi.Types
       (BiDiSinkException(BiDiSinkException, biDiSinkException_message),
        BiDiStreamException(BiDiStreamException,
                            biDiStreamException_message),
        BiDiMethodException(BiDiMethodException,
                            biDiMethodException_message))
       where
import qualified Control.DeepSeq as DeepSeq
import qualified Control.Exception as Exception
import qualified Control.Monad as Monad
import qualified Control.Monad.ST.Trans as ST
import qualified Control.Monad.Trans.Class as Trans
import qualified Data.Aeson as Aeson
import qualified Data.Aeson.Types as Aeson
import qualified Data.Default as Default
import qualified Data.HashMap.Strict as HashMap
import qualified Data.Hashable as Hashable
import qualified Data.List as List
import qualified Data.Ord as Ord
import qualified Data.Text as Text
import qualified Data.Text.Encoding as Text
import qualified Facebook.Thrift.Annotation.Thrift.Thrift.Types
       as Facebook.Thrift.Annotation.Thrift.Thrift
import qualified Prelude as Prelude
import qualified Thrift.Binary.Parser as Parser
import qualified Thrift.CodegenTypesOnly as Thrift
import Control.Applicative ((<|>), (*>), (<*))
import Data.Aeson ((.:), (.:?), (.=), (.!=))
import Data.Monoid ((<>))
import Prelude ((.), (<$>), (<*>), (>>=), (==), (/=), (<), (++))

newtype BiDiSinkException = BiDiSinkException{biDiSinkException_message
                                              :: Text.Text}
                            deriving (Prelude.Eq, Prelude.Show, Prelude.Ord)

instance Aeson.ToJSON BiDiSinkException where
  toJSON (BiDiSinkException __field__message)
    = Aeson.object ("message" .= __field__message : Prelude.mempty)

instance Thrift.ThriftStruct BiDiSinkException where
  buildStruct _proxy (BiDiSinkException __field__message)
    = Thrift.genStruct _proxy
        (Thrift.genField _proxy "message" (Thrift.getStringType _proxy) 1 0
           (Thrift.genText _proxy __field__message)
           : [])
  parseStruct _proxy
    = ST.runSTT
        (do Prelude.return ()
            __field__message <- ST.newSTRef ""
            let
              _parse _lastId
                = do _fieldBegin <- Trans.lift
                                      (Thrift.parseFieldBegin _proxy _lastId _idMap)
                     case _fieldBegin of
                       Thrift.FieldBegin _type _id _bool -> do case _id of
                                                                 1 | _type ==
                                                                       Thrift.getStringType _proxy
                                                                     ->
                                                                     do !_val <- Trans.lift
                                                                                   (Thrift.parseText
                                                                                      _proxy)
                                                                        ST.writeSTRef
                                                                          __field__message
                                                                          _val
                                                                 _ -> Trans.lift
                                                                        (Thrift.parseSkip _proxy
                                                                           _type
                                                                           (Prelude.Just _bool))
                                                               _parse _id
                       Thrift.FieldEnd -> do !__val__message <- ST.readSTRef
                                                                  __field__message
                                             Prelude.pure (BiDiSinkException __val__message)
              _idMap = HashMap.fromList [("message", 1)]
            _parse 0)

instance DeepSeq.NFData BiDiSinkException where
  rnf (BiDiSinkException __field__message)
    = DeepSeq.rnf __field__message `Prelude.seq` ()

instance Default.Default BiDiSinkException where
  def = BiDiSinkException ""

instance Hashable.Hashable BiDiSinkException where
  hashWithSalt __salt (BiDiSinkException _message)
    = Hashable.hashWithSalt __salt _message

instance Exception.Exception BiDiSinkException

newtype BiDiStreamException = BiDiStreamException{biDiStreamException_message
                                                  :: Text.Text}
                              deriving (Prelude.Eq, Prelude.Show, Prelude.Ord)

instance Aeson.ToJSON BiDiStreamException where
  toJSON (BiDiStreamException __field__message)
    = Aeson.object ("message" .= __field__message : Prelude.mempty)

instance Thrift.ThriftStruct BiDiStreamException where
  buildStruct _proxy (BiDiStreamException __field__message)
    = Thrift.genStruct _proxy
        (Thrift.genField _proxy "message" (Thrift.getStringType _proxy) 1 0
           (Thrift.genText _proxy __field__message)
           : [])
  parseStruct _proxy
    = ST.runSTT
        (do Prelude.return ()
            __field__message <- ST.newSTRef ""
            let
              _parse _lastId
                = do _fieldBegin <- Trans.lift
                                      (Thrift.parseFieldBegin _proxy _lastId _idMap)
                     case _fieldBegin of
                       Thrift.FieldBegin _type _id _bool -> do case _id of
                                                                 1 | _type ==
                                                                       Thrift.getStringType _proxy
                                                                     ->
                                                                     do !_val <- Trans.lift
                                                                                   (Thrift.parseText
                                                                                      _proxy)
                                                                        ST.writeSTRef
                                                                          __field__message
                                                                          _val
                                                                 _ -> Trans.lift
                                                                        (Thrift.parseSkip _proxy
                                                                           _type
                                                                           (Prelude.Just _bool))
                                                               _parse _id
                       Thrift.FieldEnd -> do !__val__message <- ST.readSTRef
                                                                  __field__message
                                             Prelude.pure (BiDiStreamException __val__message)
              _idMap = HashMap.fromList [("message", 1)]
            _parse 0)

instance DeepSeq.NFData BiDiStreamException where
  rnf (BiDiStreamException __field__message)
    = DeepSeq.rnf __field__message `Prelude.seq` ()

instance Default.Default BiDiStreamException where
  def = BiDiStreamException ""

instance Hashable.Hashable BiDiStreamException where
  hashWithSalt __salt (BiDiStreamException _message)
    = Hashable.hashWithSalt __salt _message

instance Exception.Exception BiDiStreamException

newtype BiDiMethodException = BiDiMethodException{biDiMethodException_message
                                                  :: Text.Text}
                              deriving (Prelude.Eq, Prelude.Show, Prelude.Ord)

instance Aeson.ToJSON BiDiMethodException where
  toJSON (BiDiMethodException __field__message)
    = Aeson.object ("message" .= __field__message : Prelude.mempty)

instance Thrift.ThriftStruct BiDiMethodException where
  buildStruct _proxy (BiDiMethodException __field__message)
    = Thrift.genStruct _proxy
        (Thrift.genField _proxy "message" (Thrift.getStringType _proxy) 1 0
           (Thrift.genText _proxy __field__message)
           : [])
  parseStruct _proxy
    = ST.runSTT
        (do Prelude.return ()
            __field__message <- ST.newSTRef ""
            let
              _parse _lastId
                = do _fieldBegin <- Trans.lift
                                      (Thrift.parseFieldBegin _proxy _lastId _idMap)
                     case _fieldBegin of
                       Thrift.FieldBegin _type _id _bool -> do case _id of
                                                                 1 | _type ==
                                                                       Thrift.getStringType _proxy
                                                                     ->
                                                                     do !_val <- Trans.lift
                                                                                   (Thrift.parseText
                                                                                      _proxy)
                                                                        ST.writeSTRef
                                                                          __field__message
                                                                          _val
                                                                 _ -> Trans.lift
                                                                        (Thrift.parseSkip _proxy
                                                                           _type
                                                                           (Prelude.Just _bool))
                                                               _parse _id
                       Thrift.FieldEnd -> do !__val__message <- ST.readSTRef
                                                                  __field__message
                                             Prelude.pure (BiDiMethodException __val__message)
              _idMap = HashMap.fromList [("message", 1)]
            _parse 0)

instance DeepSeq.NFData BiDiMethodException where
  rnf (BiDiMethodException __field__message)
    = DeepSeq.rnf __field__message `Prelude.seq` ()

instance Default.Default BiDiMethodException where
  def = BiDiMethodException ""

instance Hashable.Hashable BiDiMethodException where
  hashWithSalt __salt (BiDiMethodException _message)
    = Hashable.hashWithSalt __salt _message

instance Exception.Exception BiDiMethodException