-----------------------------------------------------------------
-- Autogenerated by Thrift
--
-- DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
--  @generated
-----------------------------------------------------------------
{-# LANGUAGE OverloadedStrings #-}
{-# LANGUAGE BangPatterns #-}
{-# OPTIONS_GHC -fno-warn-unused-imports#-}
{-# OPTIONS_GHC -fno-warn-overlapping-patterns#-}
{-# OPTIONS_GHC -fno-warn-incomplete-patterns#-}
{-# OPTIONS_GHC -fno-warn-incomplete-uni-patterns#-}
{-# OPTIONS_GHC -fno-warn-incomplete-record-updates#-}
{-# LANGUAGE GeneralizedNewtypeDeriving #-}
module H.Types
       (Hsnewtypeann_sa(Hsnewtypeann_sa, unHsnewtypeann_sa),
        HsStrictAnn_SA(HsStrictAnn_SA, hsStrictAnn_SA_strictann,
                       hsStrictAnn_SA_lazyann, hsStrictAnn_SA_inherit),
        HsLazyAnn_SA(HsLazyAnn_SA, hsLazyAnn_SA_strictann,
                     hsLazyAnn_SA_lazyann, hsLazyAnn_SA_inherit),
        HsFieldAnns_SA(HsFieldAnns_SA, hsFieldAnns_SA_strictann,
                       hsFieldAnns_SA_lazyann, hsFieldAnns_SA_inherit),
        HsUnionNonEmptyAnn_SA(HsUnionNonEmptyAnn_SA_left,
                              HsUnionNonEmptyAnn_SA_right),
        HsEnumNoUnknownAnn_SA(HsEnumNoUnknownAnn_SA_ONE,
                              HsEnumNoUnknownAnn_SA_TWO, HsEnumNoUnknownAnn_SA_THREE),
        HsEnumPseudoenumAnn_SA(HsEnumPseudoenumAnn_SA,
                               unHsEnumPseudoenumAnn_SA),
        hsEnumPseudoenumAnn_SA_ONE, hsEnumPseudoenumAnn_SA_TWO,
        hsEnumPseudoenumAnn_SA_THREE,
        HsEnumPseudoenumThriftAnn_SA(HsEnumPseudoenumThriftAnn_SA,
                                     unHsEnumPseudoenumThriftAnn_SA),
        hsEnumPseudoenumThriftAnn_SA_ONE, hsEnumPseudoenumThriftAnn_SA_TWO,
        hsEnumPseudoenumThriftAnn_SA_THREE,
        HsFoo_SA(HsFoo_SA, hsFoo_SA_baz),
        PrefixedStruct_SA(PrefixedStruct_SA, ps_foo, ps_bar),
        Map_string_string_sa, Int_sa, String_sa)
       where
import qualified Control.DeepSeq as DeepSeq
import qualified Control.Exception as Exception
import qualified Control.Monad as Monad
import qualified Control.Monad.ST.Trans as ST
import qualified Control.Monad.Trans.Class as Trans
import qualified Data.Aeson as Aeson
import qualified Data.Aeson.Types as Aeson
import qualified Data.Default as Default
import qualified Data.Function as Function
import qualified Data.HashMap.Strict as HashMap
import qualified Data.Hashable as Hashable
import qualified Data.Int as Int
import qualified Data.List as List
import qualified Data.Map.Strict as Map
import qualified Data.Ord as Ord
import qualified Data.Text as Text
import qualified Data.Text.Encoding as Text
import qualified Facebook.Thrift.Annotation.Haskell.Haskell.Types
       as Facebook.Thrift.Annotation.Haskell.Haskell
import qualified GHC.Magic as GHC
import qualified Prelude as Prelude
import qualified Thrift.Binary.Parser as Parser
import qualified Thrift.CodegenTypesOnly as Thrift
import Control.Applicative ((<|>), (*>), (<*))
import Data.Aeson ((.:), (.:?), (.=), (.!=))
import Data.Aeson ((.:), (.=))
import Data.Monoid ((<>))
import Prelude ((.), (++), (>), (==))
import Prelude ((.), (<$>), (<*>), (>>=), (==), (++))
import Prelude ((.), (<$>), (<*>), (>>=), (==), (/=), (<), (++))

newtype Hsnewtypeann_sa = Hsnewtypeann_sa{unHsnewtypeann_sa ::
                                          Map.Map Text.Text Text.Text}
                          deriving (Prelude.Eq, Prelude.Show, DeepSeq.NFData, Prelude.Ord)

instance Hashable.Hashable Hsnewtypeann_sa where
  hashWithSalt __salt (Hsnewtypeann_sa __val)
    = Hashable.hashWithSalt __salt
        ((Prelude.map (\ (_k, _v) -> (_k, _v)) . Map.toAscList) __val)

instance Aeson.ToJSON Hsnewtypeann_sa where
  toJSON (Hsnewtypeann_sa __val) = Aeson.toJSON __val

data HsStrictAnn_SA = HsStrictAnn_SA{hsStrictAnn_SA_strictann ::
                                     {-# UNPACK #-} !Int.Int32,
                                     hsStrictAnn_SA_lazyann :: Int.Int32,
                                     hsStrictAnn_SA_inherit :: {-# UNPACK #-} !Int.Int32}
                      deriving (Prelude.Eq, Prelude.Show, Prelude.Ord)

instance Aeson.ToJSON HsStrictAnn_SA where
  toJSON
    (HsStrictAnn_SA __field__strictann __field__lazyann
       __field__inherit)
    = Aeson.object
        ("strictann" .= __field__strictann :
           "lazyann" .= __field__lazyann :
             "inherit" .= __field__inherit : Prelude.mempty)

instance Thrift.ThriftStruct HsStrictAnn_SA where
  buildStruct _proxy
    (HsStrictAnn_SA __field__strictann __field__lazyann
       __field__inherit)
    = Thrift.genStruct _proxy
        (Thrift.genFieldPrim _proxy "strictann" (Thrift.getI32Type _proxy)
           1
           0
           (Thrift.genI32Prim _proxy)
           __field__strictann
           :
           Thrift.genFieldPrim _proxy "lazyann" (Thrift.getI32Type _proxy) 2 1
             (Thrift.genI32Prim _proxy)
             __field__lazyann
             :
             Thrift.genFieldPrim _proxy "inherit" (Thrift.getI32Type _proxy) 3 2
               (Thrift.genI32Prim _proxy)
               __field__inherit
               : [])
  parseStruct _proxy
    = ST.runSTT
        (do Prelude.return ()
            __field__strictann <- ST.newSTRef Default.def
            __field__lazyann <- ST.newSTRef Default.def
            __field__inherit <- ST.newSTRef Default.def
            let
              _parse _lastId
                = do _fieldBegin <- Trans.lift
                                      (Thrift.parseFieldBegin _proxy _lastId _idMap)
                     case _fieldBegin of
                       Thrift.FieldBegin _type _id _bool -> do case _id of
                                                                 1 | _type ==
                                                                       Thrift.getI32Type _proxy
                                                                     ->
                                                                     do !_val <- Trans.lift
                                                                                   (Thrift.parseI32
                                                                                      _proxy)
                                                                        ST.writeSTRef
                                                                          __field__strictann
                                                                          _val
                                                                 2 | _type ==
                                                                       Thrift.getI32Type _proxy
                                                                     ->
                                                                     do !_val <- Trans.lift
                                                                                   (Thrift.parseI32
                                                                                      _proxy)
                                                                        ST.writeSTRef
                                                                          __field__lazyann
                                                                          _val
                                                                 3 | _type ==
                                                                       Thrift.getI32Type _proxy
                                                                     ->
                                                                     do !_val <- Trans.lift
                                                                                   (Thrift.parseI32
                                                                                      _proxy)
                                                                        ST.writeSTRef
                                                                          __field__inherit
                                                                          _val
                                                                 _ -> Trans.lift
                                                                        (Thrift.parseSkip _proxy
                                                                           _type
                                                                           (Prelude.Just _bool))
                                                               _parse _id
                       Thrift.FieldEnd -> do !__val__strictann <- ST.readSTRef
                                                                    __field__strictann
                                             !__val__lazyann <- ST.readSTRef __field__lazyann
                                             !__val__inherit <- ST.readSTRef __field__inherit
                                             Prelude.pure
                                               (HsStrictAnn_SA __val__strictann __val__lazyann
                                                  __val__inherit)
              _idMap
                = HashMap.fromList
                    [("strictann", 1), ("lazyann", 2), ("inherit", 3)]
            _parse 0)

instance DeepSeq.NFData HsStrictAnn_SA where
  rnf
    (HsStrictAnn_SA __field__strictann __field__lazyann
       __field__inherit)
    = DeepSeq.rnf __field__strictann `Prelude.seq`
        DeepSeq.rnf __field__lazyann `Prelude.seq`
          DeepSeq.rnf __field__inherit `Prelude.seq` ()

instance Default.Default HsStrictAnn_SA where
  def = HsStrictAnn_SA Default.def Default.def Default.def

instance Hashable.Hashable HsStrictAnn_SA where
  hashWithSalt __salt (HsStrictAnn_SA _strictann _lazyann _inherit)
    = Hashable.hashWithSalt
        (Hashable.hashWithSalt (Hashable.hashWithSalt __salt _strictann)
           _lazyann)
        _inherit

data HsLazyAnn_SA = HsLazyAnn_SA{hsLazyAnn_SA_strictann ::
                                 {-# UNPACK #-} !Int.Int32,
                                 hsLazyAnn_SA_lazyann :: Int.Int32,
                                 hsLazyAnn_SA_inherit :: Int.Int32}
                    deriving (Prelude.Eq, Prelude.Show, Prelude.Ord)

instance Aeson.ToJSON HsLazyAnn_SA where
  toJSON
    (HsLazyAnn_SA __field__strictann __field__lazyann __field__inherit)
    = Aeson.object
        ("strictann" .= __field__strictann :
           "lazyann" .= __field__lazyann :
             "inherit" .= __field__inherit : Prelude.mempty)

instance Thrift.ThriftStruct HsLazyAnn_SA where
  buildStruct _proxy
    (HsLazyAnn_SA __field__strictann __field__lazyann __field__inherit)
    = Thrift.genStruct _proxy
        (Thrift.genFieldPrim _proxy "strictann" (Thrift.getI32Type _proxy)
           1
           0
           (Thrift.genI32Prim _proxy)
           __field__strictann
           :
           Thrift.genFieldPrim _proxy "lazyann" (Thrift.getI32Type _proxy) 2 1
             (Thrift.genI32Prim _proxy)
             __field__lazyann
             :
             Thrift.genFieldPrim _proxy "inherit" (Thrift.getI32Type _proxy) 3 2
               (Thrift.genI32Prim _proxy)
               __field__inherit
               : [])
  parseStruct _proxy
    = ST.runSTT
        (do Prelude.return ()
            __field__strictann <- ST.newSTRef Default.def
            __field__lazyann <- ST.newSTRef Default.def
            __field__inherit <- ST.newSTRef Default.def
            let
              _parse _lastId
                = do _fieldBegin <- Trans.lift
                                      (Thrift.parseFieldBegin _proxy _lastId _idMap)
                     case _fieldBegin of
                       Thrift.FieldBegin _type _id _bool -> do case _id of
                                                                 1 | _type ==
                                                                       Thrift.getI32Type _proxy
                                                                     ->
                                                                     do !_val <- Trans.lift
                                                                                   (Thrift.parseI32
                                                                                      _proxy)
                                                                        ST.writeSTRef
                                                                          __field__strictann
                                                                          _val
                                                                 2 | _type ==
                                                                       Thrift.getI32Type _proxy
                                                                     ->
                                                                     do !_val <- Trans.lift
                                                                                   (Thrift.parseI32
                                                                                      _proxy)
                                                                        ST.writeSTRef
                                                                          __field__lazyann
                                                                          _val
                                                                 3 | _type ==
                                                                       Thrift.getI32Type _proxy
                                                                     ->
                                                                     do !_val <- Trans.lift
                                                                                   (Thrift.parseI32
                                                                                      _proxy)
                                                                        ST.writeSTRef
                                                                          __field__inherit
                                                                          _val
                                                                 _ -> Trans.lift
                                                                        (Thrift.parseSkip _proxy
                                                                           _type
                                                                           (Prelude.Just _bool))
                                                               _parse _id
                       Thrift.FieldEnd -> do !__val__strictann <- ST.readSTRef
                                                                    __field__strictann
                                             !__val__lazyann <- ST.readSTRef __field__lazyann
                                             !__val__inherit <- ST.readSTRef __field__inherit
                                             Prelude.pure
                                               (HsLazyAnn_SA __val__strictann __val__lazyann
                                                  __val__inherit)
              _idMap
                = HashMap.fromList
                    [("strictann", 1), ("lazyann", 2), ("inherit", 3)]
            _parse 0)

instance DeepSeq.NFData HsLazyAnn_SA where
  rnf
    (HsLazyAnn_SA __field__strictann __field__lazyann __field__inherit)
    = DeepSeq.rnf __field__strictann `Prelude.seq`
        DeepSeq.rnf __field__lazyann `Prelude.seq`
          DeepSeq.rnf __field__inherit `Prelude.seq` ()

instance Default.Default HsLazyAnn_SA where
  def = HsLazyAnn_SA Default.def Default.def Default.def

instance Hashable.Hashable HsLazyAnn_SA where
  hashWithSalt __salt (HsLazyAnn_SA _strictann _lazyann _inherit)
    = Hashable.hashWithSalt
        (Hashable.hashWithSalt (Hashable.hashWithSalt __salt _strictann)
           _lazyann)
        _inherit

data HsFieldAnns_SA = HsFieldAnns_SA{hsFieldAnns_SA_strictann ::
                                     {-# UNPACK #-} !Int.Int32,
                                     hsFieldAnns_SA_lazyann :: Int.Int32,
                                     hsFieldAnns_SA_inherit :: Int.Int32}
                      deriving (Prelude.Eq, Prelude.Show, Prelude.Ord)

instance Aeson.ToJSON HsFieldAnns_SA where
  toJSON
    (HsFieldAnns_SA __field__strictann __field__lazyann
       __field__inherit)
    = Aeson.object
        ("strictann" .= __field__strictann :
           "lazyann" .= __field__lazyann :
             "inherit" .= __field__inherit : Prelude.mempty)

instance Thrift.ThriftStruct HsFieldAnns_SA where
  buildStruct _proxy
    (HsFieldAnns_SA __field__strictann __field__lazyann
       __field__inherit)
    = Thrift.genStruct _proxy
        (Thrift.genFieldPrim _proxy "strictann" (Thrift.getI32Type _proxy)
           1
           0
           (Thrift.genI32Prim _proxy)
           __field__strictann
           :
           Thrift.genFieldPrim _proxy "lazyann" (Thrift.getI32Type _proxy) 2 1
             (Thrift.genI32Prim _proxy)
             __field__lazyann
             :
             Thrift.genFieldPrim _proxy "inherit" (Thrift.getI32Type _proxy) 3 2
               (Thrift.genI32Prim _proxy)
               __field__inherit
               : [])
  parseStruct _proxy
    = ST.runSTT
        (do Prelude.return ()
            __field__strictann <- ST.newSTRef Default.def
            __field__lazyann <- ST.newSTRef Default.def
            __field__inherit <- ST.newSTRef Default.def
            let
              _parse _lastId
                = do _fieldBegin <- Trans.lift
                                      (Thrift.parseFieldBegin _proxy _lastId _idMap)
                     case _fieldBegin of
                       Thrift.FieldBegin _type _id _bool -> do case _id of
                                                                 1 | _type ==
                                                                       Thrift.getI32Type _proxy
                                                                     ->
                                                                     do !_val <- Trans.lift
                                                                                   (Thrift.parseI32
                                                                                      _proxy)
                                                                        ST.writeSTRef
                                                                          __field__strictann
                                                                          _val
                                                                 2 | _type ==
                                                                       Thrift.getI32Type _proxy
                                                                     ->
                                                                     do !_val <- Trans.lift
                                                                                   (Thrift.parseI32
                                                                                      _proxy)
                                                                        ST.writeSTRef
                                                                          __field__lazyann
                                                                          _val
                                                                 3 | _type ==
                                                                       Thrift.getI32Type _proxy
                                                                     ->
                                                                     do !_val <- Trans.lift
                                                                                   (Thrift.parseI32
                                                                                      _proxy)
                                                                        ST.writeSTRef
                                                                          __field__inherit
                                                                          _val
                                                                 _ -> Trans.lift
                                                                        (Thrift.parseSkip _proxy
                                                                           _type
                                                                           (Prelude.Just _bool))
                                                               _parse _id
                       Thrift.FieldEnd -> do !__val__strictann <- ST.readSTRef
                                                                    __field__strictann
                                             !__val__lazyann <- ST.readSTRef __field__lazyann
                                             !__val__inherit <- ST.readSTRef __field__inherit
                                             Prelude.pure
                                               (HsFieldAnns_SA __val__strictann __val__lazyann
                                                  __val__inherit)
              _idMap
                = HashMap.fromList
                    [("strictann", 1), ("lazyann", 2), ("inherit", 3)]
            _parse 0)

instance DeepSeq.NFData HsFieldAnns_SA where
  rnf
    (HsFieldAnns_SA __field__strictann __field__lazyann
       __field__inherit)
    = DeepSeq.rnf __field__strictann `Prelude.seq`
        DeepSeq.rnf __field__lazyann `Prelude.seq`
          DeepSeq.rnf __field__inherit `Prelude.seq` ()

instance Default.Default HsFieldAnns_SA where
  def = HsFieldAnns_SA Default.def Default.def Default.def

instance Hashable.Hashable HsFieldAnns_SA where
  hashWithSalt __salt (HsFieldAnns_SA _strictann _lazyann _inherit)
    = Hashable.hashWithSalt
        (Hashable.hashWithSalt (Hashable.hashWithSalt __salt _strictann)
           _lazyann)
        _inherit

data HsUnionNonEmptyAnn_SA = HsUnionNonEmptyAnn_SA_left Int.Int32
                           | HsUnionNonEmptyAnn_SA_right Int.Int32
                             deriving (Prelude.Eq, Prelude.Show, Prelude.Ord)

instance Aeson.ToJSON HsUnionNonEmptyAnn_SA where
  toJSON (HsUnionNonEmptyAnn_SA_left __left)
    = Aeson.object ["left" .= __left]
  toJSON (HsUnionNonEmptyAnn_SA_right __right)
    = Aeson.object ["right" .= __right]

instance Thrift.ThriftStruct HsUnionNonEmptyAnn_SA where
  buildStruct _proxy (HsUnionNonEmptyAnn_SA_left __left)
    = Thrift.genStruct _proxy
        [Thrift.genFieldPrim _proxy "left" (Thrift.getI32Type _proxy) 1 0
           (Thrift.genI32Prim _proxy)
           __left]
  buildStruct _proxy (HsUnionNonEmptyAnn_SA_right __right)
    = Thrift.genStruct _proxy
        [Thrift.genFieldPrim _proxy "right" (Thrift.getI32Type _proxy) 2 0
           (Thrift.genI32Prim _proxy)
           __right]
  parseStruct _proxy
    = do _fieldBegin <- Thrift.parseFieldBegin _proxy 0 _idMap
         case _fieldBegin of
           Thrift.FieldBegin _type _id _bool -> do case _id of
                                                     1 | _type == Thrift.getI32Type _proxy ->
                                                         do _val <- Thrift.parseI32 _proxy
                                                            Thrift.parseStop _proxy
                                                            Prelude.return
                                                              (HsUnionNonEmptyAnn_SA_left _val)
                                                     2 | _type == Thrift.getI32Type _proxy ->
                                                         do _val <- Thrift.parseI32 _proxy
                                                            Thrift.parseStop _proxy
                                                            Prelude.return
                                                              (HsUnionNonEmptyAnn_SA_right _val)
                                                     _ -> Prelude.fail
                                                            ("unrecognized alternative for union 'HsUnionNonEmptyAnn_SA': "
                                                               ++ Prelude.show _id)
           Thrift.FieldEnd -> Prelude.fail
                                "union 'HsUnionNonEmptyAnn_SA' is empty"
    where
      _idMap = HashMap.fromList [("left", 1), ("right", 2)]

instance DeepSeq.NFData HsUnionNonEmptyAnn_SA where
  rnf (HsUnionNonEmptyAnn_SA_left __left) = DeepSeq.rnf __left
  rnf (HsUnionNonEmptyAnn_SA_right __right) = DeepSeq.rnf __right

instance Default.Default HsUnionNonEmptyAnn_SA where
  def = HsUnionNonEmptyAnn_SA_left Default.def

instance Hashable.Hashable HsUnionNonEmptyAnn_SA where
  hashWithSalt __salt (HsUnionNonEmptyAnn_SA_left _left)
    = Hashable.hashWithSalt __salt (Hashable.hashWithSalt 1 _left)
  hashWithSalt __salt (HsUnionNonEmptyAnn_SA_right _right)
    = Hashable.hashWithSalt __salt (Hashable.hashWithSalt 2 _right)

data HsEnumNoUnknownAnn_SA = HsEnumNoUnknownAnn_SA_ONE
                           | HsEnumNoUnknownAnn_SA_TWO
                           | HsEnumNoUnknownAnn_SA_THREE
                             deriving (Prelude.Eq, Prelude.Show)

instance Aeson.ToJSON HsEnumNoUnknownAnn_SA where
  toJSON = Aeson.toJSON . Thrift.fromThriftEnum

instance DeepSeq.NFData HsEnumNoUnknownAnn_SA where
  rnf __HsEnumNoUnknownAnn_SA
    = Prelude.seq __HsEnumNoUnknownAnn_SA ()

instance Default.Default HsEnumNoUnknownAnn_SA where
  def = HsEnumNoUnknownAnn_SA_ONE

instance Hashable.Hashable HsEnumNoUnknownAnn_SA where
  hashWithSalt _salt _val
    = Hashable.hashWithSalt _salt (Thrift.fromThriftEnum _val)

instance Thrift.ThriftEnum HsEnumNoUnknownAnn_SA where
  toThriftEnum 1 = HsEnumNoUnknownAnn_SA_ONE
  toThriftEnum 2 = HsEnumNoUnknownAnn_SA_TWO
  toThriftEnum 3 = HsEnumNoUnknownAnn_SA_THREE
  toThriftEnum _val
    = Exception.throw
        (Thrift.ProtocolException
           ("toThriftEnum: not a valid identifier for enum HsEnumNoUnknownAnn_SA: "
              ++ Prelude.show _val))
  fromThriftEnum HsEnumNoUnknownAnn_SA_ONE = 1
  fromThriftEnum HsEnumNoUnknownAnn_SA_TWO = 2
  fromThriftEnum HsEnumNoUnknownAnn_SA_THREE = 3
  fromThriftEnum _val
    = Exception.throw
        (Thrift.ProtocolException
           ("fromThriftEnum: not a valid identifier for enum HsEnumNoUnknownAnn_SA: "
              ++ Prelude.show _val))
  allThriftEnumValues
    = [HsEnumNoUnknownAnn_SA_ONE, HsEnumNoUnknownAnn_SA_TWO,
       HsEnumNoUnknownAnn_SA_THREE]
  toThriftEnumEither 1 = Prelude.Right HsEnumNoUnknownAnn_SA_ONE
  toThriftEnumEither 2 = Prelude.Right HsEnumNoUnknownAnn_SA_TWO
  toThriftEnumEither 3 = Prelude.Right HsEnumNoUnknownAnn_SA_THREE
  toThriftEnumEither val
    = Prelude.Left
        ("toThriftEnumEither: not a valid identifier for enum HsEnumNoUnknownAnn_SA: "
           ++ Prelude.show val)

instance Prelude.Ord HsEnumNoUnknownAnn_SA where
  compare = Function.on Prelude.compare Thrift.fromThriftEnum

newtype HsEnumPseudoenumAnn_SA = HsEnumPseudoenumAnn_SA{unHsEnumPseudoenumAnn_SA
                                                        :: Int.Int32}
                                 deriving (Prelude.Eq, Prelude.Show, DeepSeq.NFData, Prelude.Ord)

instance Hashable.Hashable HsEnumPseudoenumAnn_SA where
  hashWithSalt __salt (HsEnumPseudoenumAnn_SA __val)
    = Hashable.hashWithSalt __salt __val

instance Aeson.ToJSON HsEnumPseudoenumAnn_SA where
  toJSON (HsEnumPseudoenumAnn_SA __val) = Aeson.toJSON __val

hsEnumPseudoenumAnn_SA_ONE :: HsEnumPseudoenumAnn_SA
hsEnumPseudoenumAnn_SA_ONE = HsEnumPseudoenumAnn_SA 1

hsEnumPseudoenumAnn_SA_TWO :: HsEnumPseudoenumAnn_SA
hsEnumPseudoenumAnn_SA_TWO = HsEnumPseudoenumAnn_SA 2

hsEnumPseudoenumAnn_SA_THREE :: HsEnumPseudoenumAnn_SA
hsEnumPseudoenumAnn_SA_THREE = HsEnumPseudoenumAnn_SA 3

newtype HsEnumPseudoenumThriftAnn_SA = HsEnumPseudoenumThriftAnn_SA{unHsEnumPseudoenumThriftAnn_SA
                                                                    :: Int.Int32}
                                       deriving (Prelude.Eq, DeepSeq.NFData, Prelude.Ord)

instance Hashable.Hashable HsEnumPseudoenumThriftAnn_SA where
  hashWithSalt __salt (HsEnumPseudoenumThriftAnn_SA __val)
    = Hashable.hashWithSalt __salt __val

instance Aeson.ToJSON HsEnumPseudoenumThriftAnn_SA where
  toJSON (HsEnumPseudoenumThriftAnn_SA __val) = Aeson.toJSON __val

hsEnumPseudoenumThriftAnn_SA_ONE :: HsEnumPseudoenumThriftAnn_SA
hsEnumPseudoenumThriftAnn_SA_ONE = HsEnumPseudoenumThriftAnn_SA 1

hsEnumPseudoenumThriftAnn_SA_TWO :: HsEnumPseudoenumThriftAnn_SA
hsEnumPseudoenumThriftAnn_SA_TWO = HsEnumPseudoenumThriftAnn_SA 2

hsEnumPseudoenumThriftAnn_SA_THREE :: HsEnumPseudoenumThriftAnn_SA
hsEnumPseudoenumThriftAnn_SA_THREE = HsEnumPseudoenumThriftAnn_SA 3

instance Default.Default HsEnumPseudoenumThriftAnn_SA where
  def = hsEnumPseudoenumThriftAnn_SA_ONE

instance Prelude.Show HsEnumPseudoenumThriftAnn_SA where
  showsPrec __d (HsEnumPseudoenumThriftAnn_SA __val)
    = case HashMap.lookup __val __m of
        Prelude.Just __s -> Prelude.showString __s
        Prelude.Nothing -> Prelude.showParen (__d > 10)
                             (Prelude.showString "HsEnumPseudoenumThriftAnn_SA__UNKNOWN " .
                                Prelude.showsPrec 11 __val)
    where
      __m
        = HashMap.fromList
            [(1, "HsEnumPseudoenumThriftAnn_SA_ONE"),
             (2, "HsEnumPseudoenumThriftAnn_SA_TWO"),
             (3, "HsEnumPseudoenumThriftAnn_SA_THREE")]

instance Thrift.ThriftEnum HsEnumPseudoenumThriftAnn_SA where
  toThriftEnum __val
    = HsEnumPseudoenumThriftAnn_SA (Prelude.fromIntegral __val)
  fromThriftEnum (HsEnumPseudoenumThriftAnn_SA __val)
    = Prelude.fromIntegral __val
  allThriftEnumValues
    = [hsEnumPseudoenumThriftAnn_SA_ONE,
       hsEnumPseudoenumThriftAnn_SA_TWO,
       hsEnumPseudoenumThriftAnn_SA_THREE]
  toThriftEnumEither val
    = if Prelude.elem __val Thrift.allThriftEnumValues then
        Prelude.Right __val else
        Prelude.Left
          ("toThriftEnumEither: not a valid identifier for enum HsEnumPseudoenumThriftAnn_SA: "
             ++ Prelude.show val)
    where
      __val = HsEnumPseudoenumThriftAnn_SA (Prelude.fromIntegral val)

newtype HsFoo_SA = HsFoo_SA{hsFoo_SA_baz :: Int.Int32}
                   deriving (Prelude.Eq, Prelude.Show, Prelude.Ord)

instance Aeson.ToJSON HsFoo_SA where
  toJSON (HsFoo_SA __field__baz)
    = Aeson.object ("baz" .= __field__baz : Prelude.mempty)

instance Thrift.ThriftStruct HsFoo_SA where
  buildStruct _proxy (HsFoo_SA __field__baz)
    = Thrift.genStruct _proxy
        (Thrift.genFieldPrim _proxy "baz" (Thrift.getI32Type _proxy) 2 0
           (Thrift.genI32Prim _proxy)
           __field__baz
           : [])
  parseStruct _proxy
    = ST.runSTT
        (do Prelude.return ()
            __field__baz <- ST.newSTRef Default.def
            let
              _parse _lastId
                = do _fieldBegin <- Trans.lift
                                      (Thrift.parseFieldBegin _proxy _lastId _idMap)
                     case _fieldBegin of
                       Thrift.FieldBegin _type _id _bool -> do case _id of
                                                                 2 | _type ==
                                                                       Thrift.getI32Type _proxy
                                                                     ->
                                                                     do !_val <- Trans.lift
                                                                                   (Thrift.parseI32
                                                                                      _proxy)
                                                                        ST.writeSTRef __field__baz
                                                                          _val
                                                                 _ -> Trans.lift
                                                                        (Thrift.parseSkip _proxy
                                                                           _type
                                                                           (Prelude.Just _bool))
                                                               _parse _id
                       Thrift.FieldEnd -> do !__val__baz <- ST.readSTRef __field__baz
                                             Prelude.pure (HsFoo_SA __val__baz)
              _idMap = HashMap.fromList [("baz", 2)]
            _parse 0)

instance DeepSeq.NFData HsFoo_SA where
  rnf (HsFoo_SA __field__baz)
    = DeepSeq.rnf __field__baz `Prelude.seq` ()

instance Default.Default HsFoo_SA where
  def = HsFoo_SA Default.def

instance Hashable.Hashable HsFoo_SA where
  hashWithSalt __salt (HsFoo_SA _baz)
    = Hashable.hashWithSalt __salt _baz

data PrefixedStruct_SA = PrefixedStruct_SA{ps_foo :: Int.Int64,
                                           ps_bar :: Int.Int32}
                         deriving (Prelude.Eq, Prelude.Show, Prelude.Ord)

instance Aeson.ToJSON PrefixedStruct_SA where
  toJSON (PrefixedStruct_SA __field__foo __field__bar)
    = Aeson.object
        ("foo" .= __field__foo : "bar" .= __field__bar : Prelude.mempty)

instance Thrift.ThriftStruct PrefixedStruct_SA where
  buildStruct _proxy (PrefixedStruct_SA __field__foo __field__bar)
    = Thrift.genStruct _proxy
        (Thrift.genFieldPrim _proxy "foo" (Thrift.getI64Type _proxy) 1 0
           (Thrift.genI64Prim _proxy)
           __field__foo
           :
           Thrift.genFieldPrim _proxy "bar" (Thrift.getI32Type _proxy) 2 1
             (Thrift.genI32Prim _proxy)
             __field__bar
             : [])
  parseStruct _proxy
    = ST.runSTT
        (do Prelude.return ()
            __field__foo <- ST.newSTRef Default.def
            __field__bar <- ST.newSTRef Default.def
            let
              _parse _lastId
                = do _fieldBegin <- Trans.lift
                                      (Thrift.parseFieldBegin _proxy _lastId _idMap)
                     case _fieldBegin of
                       Thrift.FieldBegin _type _id _bool -> do case _id of
                                                                 1 | _type ==
                                                                       Thrift.getI64Type _proxy
                                                                     ->
                                                                     do !_val <- Trans.lift
                                                                                   (Thrift.parseI64
                                                                                      _proxy)
                                                                        ST.writeSTRef __field__foo
                                                                          _val
                                                                 2 | _type ==
                                                                       Thrift.getI32Type _proxy
                                                                     ->
                                                                     do !_val <- Trans.lift
                                                                                   (Thrift.parseI32
                                                                                      _proxy)
                                                                        ST.writeSTRef __field__bar
                                                                          _val
                                                                 _ -> Trans.lift
                                                                        (Thrift.parseSkip _proxy
                                                                           _type
                                                                           (Prelude.Just _bool))
                                                               _parse _id
                       Thrift.FieldEnd -> do !__val__foo <- ST.readSTRef __field__foo
                                             !__val__bar <- ST.readSTRef __field__bar
                                             Prelude.pure (PrefixedStruct_SA __val__foo __val__bar)
              _idMap = HashMap.fromList [("foo", 1), ("bar", 2)]
            _parse 0)

instance DeepSeq.NFData PrefixedStruct_SA where
  rnf (PrefixedStruct_SA __field__foo __field__bar)
    = DeepSeq.rnf __field__foo `Prelude.seq`
        DeepSeq.rnf __field__bar `Prelude.seq` ()

instance Default.Default PrefixedStruct_SA where
  def = PrefixedStruct_SA Default.def Default.def

instance Hashable.Hashable PrefixedStruct_SA where
  hashWithSalt __salt (PrefixedStruct_SA _foo _bar)
    = Hashable.hashWithSalt (Hashable.hashWithSalt __salt _foo) _bar

type Map_string_string_sa = HashMap.HashMap Text.Text Text.Text

type Int_sa = Prelude.Int

type String_sa = Prelude.String