-----------------------------------------------------------------
-- Autogenerated by Thrift
--
-- DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
--  @generated
-----------------------------------------------------------------
{-# LANGUAGE OverloadedStrings #-}
{-# LANGUAGE BangPatterns #-}
{-# OPTIONS_GHC -fno-warn-unused-imports#-}
{-# OPTIONS_GHC -fno-warn-overlapping-patterns#-}
{-# OPTIONS_GHC -fno-warn-incomplete-patterns#-}
{-# OPTIONS_GHC -fno-warn-incomplete-uni-patterns#-}
{-# OPTIONS_GHC -fno-warn-incomplete-record-updates#-}
{-# LANGUAGE FlexibleContexts #-}
{-# LANGUAGE TypeFamilies #-}
{-# LANGUAGE TypeOperators #-}
module G.TU__Service.Client
       (TU__Service, doNothing, doNothingIO, send_doNothing,
        _build_doNothing, recv_doNothing, _parse_doNothing)
       where
import qualified Control.Arrow as Arrow
import qualified Control.Concurrent as Concurrent
import qualified Control.Exception as Exception
import qualified Control.Monad as Monad
import qualified Control.Monad.Trans.Class as Trans
import qualified Control.Monad.Trans.Reader as Reader
import qualified Data.ByteString.Builder as ByteString
import qualified Data.ByteString.Lazy as LBS
import qualified Data.HashMap.Strict as HashMap
import qualified Data.Int as Int
import qualified Data.List as List
import qualified Data.Proxy as Proxy
import qualified Facebook.Thrift.Annotation.Thrift.Thrift.Types
       as Facebook.Thrift.Annotation.Thrift.Thrift
import qualified Prelude as Prelude
import qualified Thrift.Binary.Parser as Parser
import qualified Thrift.Codegen as Thrift
import qualified Thrift.Protocol.ApplicationException.Types
       as Thrift
import Data.Monoid ((<>))
import Prelude ((==), (=<<), (>>=), (<$>), (.))
import G.Types

data TU__Service

doNothing ::
            (Thrift.Protocol p, Thrift.ClientChannel c,
             (Thrift.<:) s TU__Service) =>
            Foo -> Thrift.ThriftM p c s ()
doNothing __field__f
  = do Thrift.ThriftEnv _proxy _channel _opts _counter <- Reader.ask
       Trans.lift (doNothingIO _proxy _channel _counter _opts __field__f)

doNothingIO ::
              (Thrift.Protocol p, Thrift.ClientChannel c,
               (Thrift.<:) s TU__Service) =>
              Proxy.Proxy p ->
                c s -> Thrift.Counter -> Thrift.RpcOptions -> Foo -> Prelude.IO ()
doNothingIO _proxy _channel _counter _opts __field__f
  = do (_handle, _sendCob, _recvCob) <- Thrift.mkCallbacks
                                          (recv_doNothing _proxy)
       send_doNothing _proxy _channel _counter _sendCob _recvCob _opts
         __field__f
       Thrift.wait _handle

send_doNothing ::
                 (Thrift.Protocol p, Thrift.ClientChannel c,
                  (Thrift.<:) s TU__Service) =>
                 Proxy.Proxy p ->
                   c s ->
                     Thrift.Counter ->
                       Thrift.SendCallback ->
                         Thrift.RecvCallback -> Thrift.RpcOptions -> Foo -> Prelude.IO ()
send_doNothing _proxy _channel _counter _sendCob _recvCob _rpcOpts
  __field__f
  = do _seqNum <- _counter
       let
         _callMsg
           = LBS.toStrict
               (ByteString.toLazyByteString
                  (_build_doNothing _proxy _seqNum __field__f))
       Thrift.sendRequest _channel
         (Thrift.Request _callMsg
            (Thrift.setRpcPriority _rpcOpts Thrift.NormalPriority))
         _sendCob
         _recvCob

recv_doNothing ::
                 (Thrift.Protocol p) =>
                 Proxy.Proxy p ->
                   Thrift.Response -> Prelude.Either Exception.SomeException ()
recv_doNothing _proxy (Thrift.Response _response _)
  = Monad.join
      (Arrow.left (Exception.SomeException . Thrift.ProtocolException)
         (Parser.parse (_parse_doNothing _proxy) _response))

_build_doNothing ::
                   Thrift.Protocol p =>
                   Proxy.Proxy p -> Int.Int32 -> Foo -> ByteString.Builder
_build_doNothing _proxy _seqNum __field__f
  = Thrift.genMsgBegin _proxy "doNothing" 1 _seqNum <>
      Thrift.genStruct _proxy
        (Thrift.genField _proxy "f" (Thrift.getStructType _proxy) 1 0
           (Thrift.buildStruct _proxy __field__f)
           : [])
      <> Thrift.genMsgEnd _proxy

_parse_doNothing ::
                   Thrift.Protocol p =>
                   Proxy.Proxy p ->
                     Parser.Parser (Prelude.Either Exception.SomeException ())
_parse_doNothing _proxy
  = do Thrift.MsgBegin _name _msgTy _ <- Thrift.parseMsgBegin _proxy
       _result <- case _msgTy of
                    1 -> Prelude.fail "doNothing: expected reply but got function call"
                    2 | _name == "doNothing" ->
                        do let
                             _idMap = HashMap.fromList []
                           _fieldBegin <- Thrift.parseFieldBegin _proxy 0 _idMap
                           case _fieldBegin of
                             Thrift.FieldBegin _type _id _bool -> do case _id of
                                                                       _ -> Prelude.fail
                                                                              (Prelude.unwords
                                                                                 ["unrecognized exception, type:",
                                                                                  Prelude.show
                                                                                    _type,
                                                                                  "field id:",
                                                                                  Prelude.show _id])
                             Thrift.FieldEnd -> Prelude.return (Prelude.Right ())
                      | Prelude.otherwise -> Prelude.fail "reply function does not match"
                    3 -> Prelude.fmap (Prelude.Left . Exception.SomeException)
                           (Thrift.parseStruct _proxy ::
                              Parser.Parser Thrift.ApplicationException)
                    4 -> Prelude.fail
                           "doNothing: expected reply but got oneway function call"
                    _ -> Prelude.fail "doNothing: invalid message type"
       Thrift.parseMsgEnd _proxy
       Prelude.return _result